### ISSUE TITLE
Default mean flux in Lyman alpha simulations is too low

### ISSUE THREAD

**Issue by andreufont** [MP-Gadget/MP-Gadget#106]
When I run a L=10 Mpc/h box, with Ngrid=128, I get a mean flux for the Lyman alpha forest that is way too low. For instance, at z=2 I get <F> = 0.25088153839, while I should get something above 0.8 at least. 

The resolution is not too bad, so I think the box should really have a proper mean flux... Is the default UV background really off? If so, should we change the default?

**Comment by andreufont** [comment]
Actually, it might be caused by the way I'm generating the skewers using fake_spectra. I'll give an update once I've rerun the analysis following Simeon's advice.

**Comment by rainwoodman** [comment]
This is the sort of things that worries me the most... 🤦‍

**Comment by andreufont** [comment]
PR #115 fixed this (not surprisingly!). For a L=20 Mpc/h box, N=256, starting at z=99, I find a mean flux of <F>=0.7 at z=2.2. This is not perfect, since I would have expected something closer to <F>=0.8, but at least it is order of magnitude correct :-)

I think we can close this issue.

**Comment by rainwoodman** [comment]
Be aware the IC power of #115 is still wrong -- see the commit immediately after (aec3b8aff)

**Comment by andreufont** [comment]
I was using the head of master as it was a day ago, so I think it was already fixed.

**Comment by andreufont** [comment]
Hi @rainwoodman, @sbird,  
@Chris-Pedersen and I are running some Lyman alpha simulations and measuring the 3D flux power, and we started noticing again than the mean flux is systematically low. For instance, at z=3 one would expect something around <F>=0.65 (from the usual fitting functions in the literature), but from one of my L=30 Mpc/h boxes (N=256) I get things around <F>=0.5. 
If the differences were smaller I would be happy doing a rescaling of the optical depth in post-processing, but I feel like this would require too much rescaling. 
What would be the easiest way for us to change the level of UV background in the simulations?
Thanks!

**Comment by rainwoodman** [comment]
Was it at one point around 0.65 after the IC power fix? The UV background is supplied as the usual TREECOOL text file. We ship the fg_june11 version of the file. I believe after z=8-ish it assumes full ionization and it is no longer supposed to be relevant.

Could it be related to metal cooling?

**Comment by sbird** [comment]
Even at full ionization it still changes the lyman alpha forest flux. It is generally known that the FG09 models produce too low a flux and need rescaling. You can just take the TREECOOL file and multiply the columns by some constant factor. Or you can try the HaardtMadau 2015 background, or even Ewald Puchwein's recent model, which should do this automatically.

**Comment by andreufont** [comment]
@sbird - I'll try that, for now it is possible that just multiplying by a constant factor is good enough.

Thanks!

**Comment by andreufont** [comment]
Out of curiosity, why is the UV background file called TreeCool?

**Comment by sbird** [comment]
No idea - I would guess it dates back to the 90s, long before Gadget.

**Comment by rainwoodman** [comment]
Shall we add a few different Treecool files to the repo?

**Comment by sbird** [comment]
Good idea

**Comment by sbird** [comment]
I will commit a Haardt Madau 2012 background directly to master

**Comment by andreufont** [comment]
I just ran a small simulation with the HM2012 model, and the mean flux is somewhat better. It still looks low at z=4, though.

Redshift     expected      FG2011     HM2012
2.0                 0.84             0.77           0.81
2.5                 0.75             0.64           0.71
3.0                 0.65             0.49           0.57
4.0                 0.41             0.18            0.22

Expected is from the usual fitting function used in BOSS mocks, I believe from McDonald 2005.

Simulations are L=30 Mpc/h, N=256 box.

**Comment by sbird** [comment]
Yup, that looks plausible. You may, incidentally, legitimately ask whether using a widely wrong UVB makes a difference for galaxy formation simulations :)

**Comment by andreufont** [comment]
In case others are curious, if you double HM2012 you get quite close.

Redshift expected FG2011 HM2012 HM2012(x2)
2.0         0.84         0.77          0.81         0.87
2.5         0.75         0.64          0.71         0.80
3.0         0.65         0.49          0.57         0.69
4.0         0.41          0.18          0.22         0.37

**Comment by sbird** [comment]
Interesting! We should try the Puchwein 2017 UVB as well - and maybe make something that works the default.

**Comment by andreufont** [comment]
Hi @sbird , I talked about this with @jonorbe, and he sent me a few extra tree_cool files that I will try to see what mean flux I get.

**Comment by jonorbe** [comment]
Hello,

I think that Figure 9 of  https://arxiv.org/abs/1607.04218 can be helpful in this discussion. There are also several discussions regarding the mean flux in hydro sims in that paper that you may find useful. I think that if you use Puchwein's you are going to get a much better match with the mean flux. In fact I attach here a plot updating Figure 9 of my paper which includes the new Puchwein+18 model (all runs are 20 Mpc/h, 1024^3). 

[meanflux_z_new.pdf](https://github.com/rainwoodman/MP-Gadget/files/1951314/meanflux_z_new.pdf)

Do not take the "fit to observations" of that plot too seriously. It was just an attempt to get a simple analytical fit to the mean flux that could be used at all redshifts (you can check Figure 8 if you want). 
I will argue that Puchwein's model fits better Becker measurements at 4< z< 4.8 but is slightly higher to the values measured at z>5 (you can also see this in their Figure 6). 

Hope it helps. Happy to iterate.

**Comment by andreufont** [comment]
Could anyone add a link to the tree_cool file from Puchwein?

**Comment by jonorbe** [comment]
Here it is

[TREECOOL_P18.txt](https://github.com/rainwoodman/MP-Gadget/files/1951615/TREECOOL_P18.txt)

**Comment by sbird** [comment]
Welcome, jonorbe. I would not be averse to making the Puchwein 2018 model the default, actually. But perhaps we should wait for their paper to be refereed first, in case it changes a bit.

**Comment by sbird** [comment]
I also notice that the Puchwein paper has two UVBs, one for equilibrium and one for non-equilibrium ionization solvers, which would be useful if we add a non-equilibrium mode at some point.

**Comment by andreufont** [comment]
Here is a plot summarizing my tests on mean flux. 

All simulations used the same initial conditions (Planck cosmology) and had a box L=30 Mpc/h and N=256, started at z=99.

![mean_flux](https://user-images.githubusercontent.com/3873863/39369758-116e8848-4a35-11e8-9d57-429b9fbabf67.png)

The line showing the BOSS mocks shows some rough fit to observations, I believe based on McDonald et al. (2005). We don't need to match it exactly, but it is nice to see that both Puchwein et al. (2018) and Onorbe et al. (2016) are much closer to it. 

Ideally we would also look at the predicted temperatures, and some fit of T_0 and gamma as a function of redshift. @sbird  - I forgot if there is code to fit these in fake_spectra, otherwise we could add it.

**Comment by sbird** [comment]
There is an old script to do it here:
https://github.com/sbird/DLA_script/blob/master/gamma.py
but it only works on arepo snapshots. I'm pretty sure I made an updated version for MP-Gadget at some point, but I'm afraid I can't find it anymore. Pull requests for fake_spectra welcome!
