### ISSUE TITLE
Effect of Displacment constraint on PM step size.

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#111]
Moved from #110.

No I don't really know why they are not using the simpler formula. I will ask around.

The bottom line is to show that with the displacement constraint, non-physical fluctuation is obtained due to fluctuation in number of time steps. This is hard to show directly, because the response is is non-linear even at very small-k (we are looking at something 1e-5 or 1e-6). 

We can establish this a good evidence of it with two arguments:

first, we want to show that even with the displacement constraint, adding more PM steps alters the resulting power spectrum, even at large scale.
second, we show with small perturbations the total number of PM steps changes.

**Comment by sbird** [comment]
I bumped into Katrin Heitmann today and asked her what HACC does: she said (somewhat surprisingly) that HACC just evenly spaces the timesteps, and you specify in advance where you want them to be. HACC also does not do adaptive timestepping except in the hydro solver.

**Comment by rainwoodman** [comment]
Not doing adaptive timestepping? That's a bit strange... So tree force of all particles are calculated every step?

**Comment by sbird** [comment]
That's what she said - her reason was that it is easy to introduce inaccuracies when doing anything else (which is I guess true, as we discovered with the dynamic tree...).

**Comment by sbird** [comment]
I checked shrinking the RMSDisplacementFac by a factor of 4 and found an increase in total power of about 0.3%. This is not important but is not zero either. I might shrink the default slightly.

**Comment by sbird** [comment]
I have checked the effect of decreasing MaxRMSDisplacementFac from 0.2 to 0.1 and it increases total power by 0.05%. This is very small. I guess the effect above is because I also shrunk MaxSizeTimestep from 0.1 to 0.025 which has a bigger effect at high redshift.

**Comment by rainwoodman** [comment]
If we really care we shall add the FastPM factors to PM kick and drift. I've been thinking of doing this for a very long time -- it may actually allow us to get away with much longer PM steps, since in that case we would only care about the small scale motion rather than trying to recover the linear scale motion.

**Comment by sbird** [comment]
Ah yes. That could help especially at high redshift. But I think the bottom line here is that this is not essential - what we have seems to be fine. I may decrease the default MaxSizeTimestep a little, especially if it makes P_b/P_cdm better, and then I will close this. If you want to add the FastPM factors though, by all means go ahead!

**Comment by sbird** [comment]
I have checked MaxSizeTimestep and it doesn't make any difference to P_b/P_cdm. Setting MaxSizeTimestep = 0.05 increases the total power by 0.2%. I am happy with saying that the design accuracy of the code is ~ 0.5% (the cosmic variance is in any case larger than that) and so we should leave these parameters as they are. I will add a comment in the parameter file and I will close this.
