### ISSUE TITLE
A converter between bigfile and Gadget-1/2 snapshots

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#122]
- To ease integration with legacy pipelines that uses Gadget-2;
- Can be a python script (light dependency -- aka not depending on nbodykit);
- must run on python 2.7 and 3+, both.

**Comment by rainwoodman** [comment]
On the other hand, if it depends on nbodykit it will be less than 10 lines... Why don't I start with something like that..

**Comment by rainwoodman** [comment]
See also, https://github.com/MP-Gadget/MP-Gadget/pull/232

**Comment by sbird** [comment]
We have a converted between HDF5 and Gadget-3 itself can convert HDF5 to Gadget format so let's close this.
