### ISSUE TITLE
Unify parameter files regardless of compilation options

### ISSUE THREAD

**Issue by andreufont** [MP-Gadget/MP-Gadget#147]
Right now, if you compile MP-Gadget with the flag:
OPT += -DBLACK_HOLES
you will need to specify in paramfile.gadget the option:
BlackHoleOn = 0

However, if you compile MP-Gadget without the flag, the code will crash if you have BlackHoleOn defined in your parameter file. 

Ideally, if you have BlackHoleOn = 0 on your parameter file, but you did not compile with DBLACK_HOLES, it would just ignore it.

**Comment by rainwoodman** [comment]
Ideally the parser shall ignore module specific parameters when a flag is set to disabled. Currently we are making all module specific parameters 'optional' to make it 'apparently working'. So if any REQUIRED parameter leaks into param.c it will be broken again.

Let's keep this Open till we can actually handle the dependency of parameter existence.

**Comment by sbird** [comment]
Ok, I'm closing this since we don't have any compile flags anyway anymore. We still don't have module specific parameters but I don't think we're going to.
