### ISSUE TITLE
Adaptive Gravitational Softening

### ISSUE THREAD

**Issue by sbird** [MP-Gadget/MP-Gadget#179]
I am opening this bug to keep track of my investigation into whether adaptive softening should be the default for baryons. https://arxiv.org/abs/1301.7426 claims that it should be, in order to reproduce the ratio between CDM and baryons. However, it also disables all hydro for the baryons, which raises the question as to why, exactly, there should be adaptive softenings for the baryons but not the CDM. FIRE-2 also uses adaptive softenings by default, but I think that is for a different reason: so that particles which cool until they reach high densities can have a smaller softening length.

I have performed some test simulations, with the default ("all softenings equal"), adaptive softenings, and with non-adaptive softenings but a doubled softening length for the baryons. I also tried decreasing the tree error tolerance, but that had no effect.

Below are results at z=49, z=9 and z=4.2. Box size is 512 Mpc, particle load is 512^3, ICs at z=99.

Default:
![part_000](https://user-images.githubusercontent.com/1325948/34075087-fbf631c2-e289-11e7-986b-cd0461da0da5.png)
![part_001](https://user-images.githubusercontent.com/1325948/34075088-00c763f6-e28a-11e7-8e04-a4c967d960de.png)
![part_003](https://user-images.githubusercontent.com/1325948/34075103-66fb45e8-e28a-11e7-8a87-c497818ad014.png)
See that we reproduce the extra power seen in 1301.7426.

Adaptive softenings:
![part_000](https://user-images.githubusercontent.com/1325948/34075098-54c38890-e28a-11e7-9287-f8f37026f090.png)
![part_001](https://user-images.githubusercontent.com/1325948/34075099-55ea1a2c-e28a-11e7-8acf-640328c15dad.png)
![part_002](https://user-images.githubusercontent.com/1325948/34075105-732ff4b2-e28a-11e7-8cd5-c54db8b630bf.png)
The baryon/CDM ratio is better reproduced at z=49, but by z=4.2 the two simulations are basically identical.

Baryon softenings == mean interparticle spacing: 
![part_000](https://user-images.githubusercontent.com/1325948/34075113-bbc4ac54-e28a-11e7-9371-400fcbb6561e.png)
![part_001](https://user-images.githubusercontent.com/1325948/34075114-bbcd4a76-e28a-11e7-9890-6fe79200fcd1.png)
Note that these lines are identical to the adaptive softenings on large scales, but have less small scale suppression (because the mean softening is smaller).

It seems (surprisingly) that Angulo is wrong and adaptive softening is not really the answer - but I am not sure what is. At early times the code is much faster with any option other than the default.

To check:
- How much do we have to increase baryon softenings by: Still happens at 1/10. Not MixedSoftenings.
- Does it help if we give the gas a uniform relative velocity, ala Tsielevitch & Hirata?
- Is there a way to reproduce the baryon/CDM ratio even at z=4.2?

**Comment by sbird** [comment]
Correction above: the "increased softening" is actually GravitySofteningGas = 1, not 1/15.
So it seems that the softening must be increased substantially (and we still don't really get the offset right). A larger box may help.

**Comment by sbird** [comment]
I think this may be due to our use of the same velocity prefactors for gas and dark matter. By numerically differentiating CAMB, 1610.08501 get good agreement with the linear transfer functions without using adaptive softenings.

**Comment by rainwoodman** [comment]
I agree it doesn't really seem to be adaptive smoothing. At high redshift it is possible that the adaptive smoothing modified the estimation of power spectrum (different aliasing due to different > nyquist power) to give you this false impression of better agreement.
I don't remember how much the radiation drag term affects the high redshift solution. In n-body it probably corresponds to the UV heating.

For big boxes, another issue is that at high redshift the horizon kicks in really early. If you seed the initial condition with a relativistic solution at high z there will be missing power at large scale (Gpc ish) at late time -- what do you do with this? 

REPS advocates rescaling the transfer functions again to match the very large scale power.
Another choice (that I wanted to try) is to start the simulation with an inconsistent velocity for all particle species such that the linear solution of 3-fluid matches the non-relativistic solution at all scales. This involves solving the 3-fluid linear model backward from late time.

**Comment by sbird** [comment]
Right, so we aren't really dealing with horizon-scale effects (my solution has always been: don't run large boxes, which is probably not a good long-run idea). This paper: https://arxiv.org/abs/1610.04236 adds radiation perturbations (generated using CLASS) to the power on large scales, which is an idea I quite like. I'm generally opposed to rescaling the transfer functions as it gets kind of messy with multiple fluids.

I also checked with Matt McQuinn, who told me that the relative velocity effect shouldn't show up unless the mass resolution is ~10^4 . Also relative velocity simulations have so far only been run for boxes of around 10 Mpc. If your box is larger than 100 Mpc you include them automatically because you have the large-scale modes that generate them.

**Comment by rainwoodman** [comment]
My understanding of 1610.04236 is that they say adding the GR term makes the linear behaviour correct comparing to a relativistic linear solver -- including the horizon effect as well. (due to the added potential term). So it looks like the single correct thing to do here.

**Comment by sbird** [comment]
Closing, continuing in #211 for the remaining tree inaccuracy.
