### ISSUE TITLE
Compilation without OPENMP_USE_SPINLOCK

### ISSUE THREAD

**Issue by sbird** [MP-Gadget/MP-Gadget#217]
I noticed that if you do not define OPENMP_USE_SPINLOCK there is a compilation error:

/home/spb/codes/MP-Gadget/libgadget/fof.c:446: undefined reference to `lock_particle'
/home/spb/codes/MP-Gadget/libgadget/fof.c:453: undefined reference to `unlock_particle'

either we should provide workable definitions for lock_particle and unlock_particle in drift.c even without spinlocks , or we should force OPENMP_USE_SPINLOCK to be always on and remove the define.

Relatedly, we found that mac does not define pthread_spinlock_t which makes OPENMP_USE_SPINLOCK fail. If we decide to make this compiel flag always on, we should provide an alternative implementation, perhaps typedeffing pthread_spinlock_t to pthread_mutex_t , or providing a stub implementation, or using omp_set_lock instead.

Yu, what do you think?

**Comment by sbird** [comment]
We could perhaps use preprocessor magic to make lock_particle a critical section, but that seems less neat than just providing an omp_set_lock backup. 

I am guessing that a spinlock is better than a mutex (which seems to be what omp_set_lock is implemented using) because there is no need to sequentially wake the threads with a spinlock.

**Comment by rainwoodman** [comment]
no spin locks on mac? i thought it is par of posix.

We can probably cook something with cmpexchg on intel macs.

or perhaps say on macs we will never run with more than one thread?

**Comment by sbird** [comment]
That's what I thought too, but apparently not... I can definitely cook something for mac - no need to go cmpexchg, I think, because we don't really care about performance there.

The main issue is whether to keep OPENMP_USE_SPINLOCK and fix compilation if it is disabled, or whether to just remove it. What do you think?

**Comment by sbird** [comment]
I think the only reason to disable OPENMP_USE_SPINLOCK really is if OPENMP is disabled. Then you save a bit of memory in struct particle_data (or maybe you are using a compiler without openmp). So how about I make OPENMP_USE_SPINLOCK a synonym for _OPENMP? Then on platforms, like mac, where it doesn't work well, we can just compile without openmp and use 1 thread.
