### ISSUE TITLE
Scary comparison

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#247]
https://arxiv.org/abs/1810.02916

figure 5.

@sbird

**Comment by sbird** [comment]
Yes - I saw the paper when it came out. There is a link in the cited original comparison to the parameter files they use, but it is broken. We should add an MP-Gadget example to do that simulation and check at what level it agrees.

**Comment by rainwoodman** [comment]
Here is the link:

https://www.ics.uzh.ch/~aurel/euclid.htm

**Comment by sbird** [comment]
Fixed by #248
