### ISSUE TITLE
Add option for primordial running in GenIC

### ISSUE THREAD

**Issue by andreufont** [MP-Gadget/MP-Gadget#255]
Currently GenIC can handle different amplitude and slope of primordial power, but not running. We need to be able to modify this in the context of Lyman alpha emulators, and I think it should be fairly easy to fix, but before I get hands on adding this feature I'd like to hear from the experts.

PS: I was going to use PrimordialRunning as option in GenIC config files.

**Comment by Chris-Pedersen** [comment]
I'll send a PR with this shortly!
