### ISSUE TITLE
make_class_power.py crashing with certain inputs

### ISSUE THREAD

**Issue by Chris-Pedersen** [MP-Gadget/MP-Gadget#264]
We're getting an odd crash of make_class_power.py with a seemingly innocuous cosmology:

```
[dc-pede1@login-e-14 ~]$ python3 ~/Codes/MP-Gadget-Master/tools/make_class_power.py parambroke.genic
Traceback (most recent call last):
  File "/home/dc-pede1/Codes/MP-Gadget-Master/tools/make_class_power.py", line 240, in <module>
    make_class_power(args.paramfile, args.extpk, args.extraz,args.verbose)
  File "/home/dc-pede1/Codes/MP-Gadget-Master/tools/make_class_power.py", line 183, in make_class_power
    powspec = CLASS.Spectra(engine)
  File "classylss/binding.pyx", line 1174, in classylss.binding.Spectra.__init__
  File "classylss/binding.pyx", line 278, in classylss.binding.ClassEngine.compute
classylss.binding.ClassBadValueError: perturb_init(L:392) :error in perturb_solve(ppr, pba, pth, ppt, index_md, index_ic, index_k, pppw[thread]);
=>perturb_solve(L:2440) :error in generic_evolver(perturb_derivs, interval_limit[index_interval], interval_limit[index_interval+1], ppw->pv->y, ppw->pv->used_in_sources, ppw->pv->pt_size, &ppaw, ppr->tol_perturb_integration, ppr->smallest_allowed_variation, perturb_timescale, ppr->perturb_integration_stepsize, ppt->tau_sampling, tau_actual_size, perturb_sources, perhaps_print_variables, ppt->error_message);
=>evolver_ndf15(L:296) :error in new_linearisation(&jac,hinvGak,neq,error_message);
=>new_linearisation(L:967) :condition (funcreturn == _FAILURE_) is true; Failure in sp_ludcmp. Possibly singular matrix!
```

I've attached the paramfile.genic here:

[paramfile_broken_genic.txt](https://github.com/MP-Gadget/MP-Gadget/files/3034463/paramfile_broken_genic.txt)

I've tried plugging these values directly into CLASS and didn't get any problem, although there might be some hidden tolerance/accuracy parameters that were different. What's also strange is that making changes to cosmology params makes the issue go away, for example if you change HubbleParam to 0.6724 it works. I suspect the issue lies in the way that the params are being passed to CLASS, but I'm not sure, I don't see why making small changes to cosmology would break the integration, what do you think?

**Comment by sbird** [comment]
That is rather weird. The accuracy parameters we're pushing to class are quite high, which could be the problem. All make_class_power.py really does is to pass these parameters to classylss and thence to class, so you might try printing them to terminal and then passing them directly to classylss/class. Maybe it is a bug in classylss?

**Comment by Chris-Pedersen** [comment]
I tried lowering the accuracy parameters and it didn't make any difference. I think a bug is in classylss is most likely, I will be able to take another look a bit later in the week.

**Comment by rainwoodman** [comment]
Could be useful if we print the class param dictionary generated by classylss:
in either `.pars`, or `.parameter_file` attribute of the cosmology object.

**Comment by andreufont** [comment]
Any progress on this? It only happens for few cosmological models, but it is scary... it might be pointing to a much bigger issue.

**Comment by rainwoodman** [comment]
Indeed. I will investigate the crash this week; we also need an update to the bundled version of class in classylss, which may solve this issue. @Chris-Pedersen which version of stand-alone CLASS were you using when you say it worked?

**Comment by andreufont** [comment]
In case it helps, here you have another configuration file that crashes with the following error:
Traceback (most recent call last):
  File "/home/dc-pede1/Codes/MP-Gadget-Stable/tools/make_class_power.py", line 240, in <module>
    make_class_power(args.paramfile, args.extpk, args.extraz,args.verbose)
  File "/home/dc-pede1/Codes/MP-Gadget-Stable/tools/make_class_power.py", line 183, in make_class_power
    powspec = CLASS.Spectra(engine)
  File "classylss/binding.pyx", line 1174, in classylss.binding.Spectra.__init__
  File "classylss/binding.pyx", line 278, in classylss.binding.ClassEngine.compute
classylss.binding.ClassBadValueError: perturb_init(L:392) :error in perturb_solve(ppr, pba, pth, ppt, index_md, index_ic, index_k, pppw[thread]);
=>perturb_solve(L:2440) :error in generic_evolver(perturb_derivs, interval_limit[index_interval], interval_limit[index_interval+1], ppw->pv->y, ppw->pv->used_in_sources, ppw->pv->pt_size, &ppaw, ppr->tol_perturb_integration, ppr->smallest_allowed_variation, perturb_timescale, ppr->perturb_integration_stepsize, ppt->tau_sampling, tau_actual_size, perturb_sources, perhaps_print_variables, ppt->error_message);
=>evolver_ndf15(L:474) :error in new_linearisation(&jac,hinvGak,neq,error_message);
=>new_linearisation(L:967) :condition (funcreturn == _FAILURE_) is true; Failure in sp_ludcmp. Possibly singular matrix!

--- param file ---

Ngrid = 64 
BoxSize = 31264.448715 
Redshift = 99.000000 
Seed = 123 
InvertPhase = 1 
OutputDir = output 
FileBase = IC 
ProduceGas = 1 
RadiationOn = 1 
DifferentTransferFunctions = 1 
ScaleDepVelocity = 1 
UnitaryAmplitude = 1 
FileWithInputSpectrum = matterpow.dat 
FileWithTransferFunction = transfer.dat 
Omega0 = 0.363184 
OmegaLambda = 0.636816 
OmegaBaryon = 0.056268 
HubbleParam = 0.625289 
MNue = 0.0 
MNum = 0.0 
MNut = 0.0 
Sigma8 = -1 
InputPowerRedshift = -1 
WhichSpectrum = 2 
PrimordialIndex = 0.899390 
PrimordialAmp = 2.566163e-09 
PrimordialRunning = 4.163300e-02 
UnitLength_in_cm = 3.085678e21 
UnitMass_in_g = 1.989e43 
UnitVelocity_in_cm_per_s = 1e5

**Comment by Chris-Pedersen** [comment]
I was using [this commit](https://github.com/lesgourg/class_public/commit/de7d9d7e54874dd7c841ee6896cf39ded32e2bae) when running with the executable. I matched as many parameters as I could from the paramfile.genic, however there are many others that might not have been matched as they might be set to something else inside classylss (tolerance settings etc). I think a stronger argument for this not being in CLASS itself is just the amount that its been used by other people; if certain combinations of cosmology params caused this crash surely it would have been noticed already.

**Comment by andreufont** [comment]
Just to add to what @Chris-Pedersen says: I just tried to use make_class_power for 10 cosmolgies and got a crash for 3 of them.

**Comment by rainwoodman** [comment]
Would be nice if you can share all of the 10 cosmlogies (failed and working
ones) such that I can have a better sense when looking at it.

**Comment by rainwoodman** [comment]
@Chris-Pedersen I think it is the same version we use in classylss. Must be some flags classylss adds that is causing the problem.

**Comment by rainwoodman** [comment]
This worked on the first paramfile : paramfile_broken_genic.txt :
https://github.com/MP-Gadget/MP-Gadget/pull/270
Let me how it goes!

**Comment by andreufont** [comment]
Hi @rainwoodman - thanks for fixing this so quickly! It looks like a reasonable explanation, and very reasonable fix. None will ever care about Omega_k < 1e-9.  I might not be able to try the other cosmologies until Monday, but I'm quite sure this will work.

**Comment by Chris-Pedersen** [comment]
Great thanks Yu! I'll close as this looks like it'll fix it.

**Comment by andreufont** [comment]
Hi @rainwoodman - I finally managed to add the 10 models, hopefully now they all run

[genic_10.tar.gz](https://github.com/MP-Gadget/MP-Gadget/files/3118018/genic_10.tar.gz)
