### ISSUE TITLE
Low beta in Lya forest simulations

### ISSUE THREAD

**Issue by Chris-Pedersen** [MP-Gadget/MP-Gadget#295]
Hi! @andreufont  and I have been looking at the bias in our simulations by looking at the ratio P_3D(k, \mu)/P_linear(k), and think that the sims we've been running have unusually low beta.

For example, this Planck L=60 Mpc/h, 512**3 particle hydro sim with quickLya on running on[ this commit](https://github.com/MP-Gadget/MP-Gadget/search?q=9565f64b4e&type=Commits), gives:

![bias_z3](https://user-images.githubusercontent.com/16047009/58435898-b296a400-80ba-11e9-9268-f93afa4f6d44.png)
![bias_z2_8](https://user-images.githubusercontent.com/16047009/58435897-b296a400-80ba-11e9-899b-de991158d718.png)
![bias_z2_2](https://user-images.githubusercontent.com/16047009/58435896-b296a400-80ba-11e9-8586-e1a96ea442cf.png)

If we compare this to the Sherwood simulations at the same redshfit:

![Sherwood_2_8](https://user-images.githubusercontent.com/16047009/58435939-d0fc9f80-80ba-11e9-83a5-5c61c09f05d7.png)

We see that there's a lot larger spread for different \mu values, meaning that beta appears to be much lower in the MP-gadget simulations. If we compare to some previous papers, in https://arxiv.org/abs/1506.04519:

![arinyo_z2_2](https://user-images.githubusercontent.com/16047009/58436190-005fdc00-80bc-11e9-87f9-4ad46630f554.png)
![arinyo_z3](https://user-images.githubusercontent.com/16047009/58436191-005fdc00-80bc-11e9-86c0-831e85a91627.png)

and in https://arxiv.org/abs/astro-ph/0108064:

![macdonald_bias](https://user-images.githubusercontent.com/16047009/58436217-1c637d80-80bc-11e9-9889-a430d89b237c.png)

we also seem to see a higher beta more consistent with the other simulations. I'll calculate bias and beta this week so we can compare numbers, but by eye the trend seems quite strong, what do you think? @keirkwame do you have any thoughts on this?

**Comment by sbird** [comment]
Maybe? It looks like a factor of two, but think we need some numbers. I'd also want to be sure you are using the same cosmology for each simulation. Do you have intuition as to what beta is measuring? ie, is it the gravity? sigma_8? Or the thermal physics?

**Comment by andreufont** [comment]
Hi @sbird - by eye, it looks like beta in the plots is of order ~ 0.5, much smaller than any other simulation. In appendix A of [Arinyo-i-Prats et al. (2015) ](https://arxiv.org/abs/1506.04519) there are many tables reporting values of bias/beta for different cosmology, different IGM models, different simulation code (SPH vs Eulerian)... but all the values are in the range 1.0 < beta < 1.6, and most of them are in the range 1.2 < beta < 1.5.

**Comment by andreufont** [comment]
Given that when we run the same code on Sherwood and Illustris simulations we get reasonable results, I suspect the source of the low value of beta is in MP-Gadget, or in how fake_spectra reads BigFile (the other simulations use HDF5).

An interesting test would be to plot the anisotropic power spectrum of matter (we should measure bias_eta=0), and the power spectrum of redshift space distorted matter (we should measure bias_eta=1). Not sure how difficult it would be to modify fake_spectra to be able to do this.

**Comment by keirkwame** [comment]
The beta looks a little low but I agree with Simeon that numbers would be helpful - there's some code in my lyman-alpha repo that can do this. from my experience of the literature on this, accurately simulating large-scale bias in forest simulations is tricky. also, with a 60 Mpc/h box, the largest-scale modes are still only quasi-linear so an accurate fit is also tricky. andreu's tests are sensible - i also have a version of GenPK that can measure the matter power as a function of mu which i can share. considering that beta is (partly) determined by large-scale velocity flows, it may also be worth looking at the velocity power spectrum - perhaps this is linked to the initial conditions problem with DM/baryons?

**Comment by sbird** [comment]
My point is that we need some numerical fits to narrow this down. It looks by eye like the overall bias, b, is also low compared to Sherwood (but not compared to McDonald) but I cannot really tell how much lower just from the plots. From the tables it looks like beta depends in a complex way on a variety of cosmological parameters, so more information is needed to understand what is happening.

You should plot the ratio of the non-linear matter power spectrum from the code to the matter power spectrum from halofit to check the gravity. fake_spectra doesn't do anisotropic power spectra, but you can do it with genpk or (probably more easily) with nbodykit. The temperature density plot as well, to check that the temperature and the slope of the temperature-density relation is roughly correct.

As Keir suggests, checking that a run with ScaleDepVelocity = 0 and DifferentTransferFunctions = 0 produces a similar beta would also be important (if it does not, that's something we should publish).

One last thing: be sure that you have DensityIndependentSphOn = 0 and DensityKernelType = cubic because fake_spectra doesn't support higher order kernels.

**Comment by Chris-Pedersen** [comment]
>As Keir suggests, checking that a run with ScaleDepVelocity = 0 and DifferentTransferFunctions = 0 produces a similar beta would also be important (if it does not, that's something we should publish).

Running some tests on these now - and I have been using DensityIndependentSphOn = 0 and DensityKernelType = cubic.  In the meantime, in dashed lines below I've fit bias and beta for a L90, 1024^3 particle sim for a Planck cosmology run in MP-Gadget and compared with the L80, 1024^3 particle Sherwood simulation, running the same script on both. The mean flux is fixed to < F > = 0.696 for both sets of flux skewers, which is the same as Fig. 11 in https://arxiv.org/abs/1506.04519. To avoid running a whole 10-dimensional MCMC I'm fitting only the linear parameters, only using k bins to the left of the dashed grey line, with the same set of hardcoded non-linear parameters used in both plots.

![MP_gadget_bias_L90_MF_0696](https://user-images.githubusercontent.com/16047009/58984882-06e40700-87d2-11e9-89f0-fcc65453f23e.png)
![SherwoodBias_L80_MF_0696](https://user-images.githubusercontent.com/16047009/58985307-ea949a00-87d2-11e9-8a8b-75ed51fe7c79.png)

Fig 11 from Arinyo-y-Prats looks consistent with the Sherwood results but not with MP-Gadget:

![fig11_arinyo](https://user-images.githubusercontent.com/16047009/58985202-b8833800-87d2-11e9-8f4b-dd6e3a17d756.png)

I'll also see if I can generate the same plot from my own Gadget-3 simulation.

**Comment by sbird** [comment]
Thanks for the fit!

So it is only beta, not b that is different. That's odd. I am wondering if something is happening with the velocity field, which would be added to the line-of-sight power differently from the off-line-of-sight power, but I don't see how that could be the case without screwing up the growth function.

Could you generate a matter power spectrum for both CDM and baryons from the same snapshot and compare it to linear theory?

**Comment by andreufont** [comment]
Hi @sbird - we were talking about this with Chris and Keir earlier today, and here are some thoughts:
 - the problem can be read as beta being a factor of 2.5 too low.
 - this can be translated to the velocities being a factor of 2.5 too low.
 - as you mentioned, if this was true in MP-Gadget itself, the linear growth would be really off. 
 - the error could be in fake_spectra or in our code to measure the 3D flux power, but we use the same code to measure the power spectrum in Sherwood.
 - the only difference between the analysis in Sherwood and in our MP-Gadget simulations is that they use different snapshot format (HDF5 vs BigFile). That would be my first guess at where the issue might be.

**Comment by andreufont** [comment]
Things that would be useful to debug this further:
 - measure the velocity power spectrum of the snapshots, and compare to linear theory. 
 - measure the power spectrum of matter, in redshift space. Not sure whether GenPK or Nbodykit can do that. 
 - use fake_spectra to interpolate to compute the optical depth in redshift space, and measure the 3D power spectrum of the optical depth. If there are no bugs, we should find beta_tau = f / bias_tau.

**Comment by sbird** [comment]
fake_spectra just reads the Velocity array directly from the snapshots. It is possible that there is some subtle change in the definition, but there is an easy way to check this. You could just make a histogram of |v|^2 in both Sherwood and your snapshots and see if they roughly agree. If they were off by a factor of 2.5 that should show up somewhere.

You could make a similar histogram of the smoothing length, in case the definition of that is different.

**Comment by sbird** [comment]
Stupid things to check would be:
1) Do we have a factor of 2 difference in the definition of the smoothing length.
2) Do we have a factor of sqrt(a) in the definition of Velocity.

**Comment by andreufont** [comment]
Hi @sbird - Why would the smoothing length change the linear velocities?

We could look at the histogram of velocities, but we don't have a linear thoery prediction for that, since it is affected by non-linearities and the resolution of the simulation. Power spectra are not.

Another hint at velocities being too small: the line of sight power (purple lines) is suppressed at high-k by peculiar velocities. In MP-Gadget plots the suppression happens at a k higher than usual, pointing again at peculiar velocities being too small.

**Comment by andreufont** [comment]
I've compared histogram of velocities from two simulations:
 - Sherwood (L=80 Mpc/h, N=1024, z=2.8)
 - MP-Gadget (L=60 Mpc/h, N=512, z=2.75)
 - MP-Gadget (L=10 Mpc/h, N=512, z=2.75)

![velocities](https://user-images.githubusercontent.com/3873863/59036174-b23e9b80-8866-11e9-8c8d-024f23b38812.png)

The histograms are very different! There is some dependency on box size / resolution, but I do think we have a problem in the velocities...

**Comment by andreufont** [comment]
@sbird - In all our runs we have these lines in the parameter file. How do they look?

# defines length unit of tabulated input spectrum in cm/h.
UnitLength_in_cm = 3.085678e21   # defines length unit of output (in cm/h)
UnitMass_in_g = 1.989e43      # defines mass unit of output (in g/cm)
UnitVelocity_in_cm_per_s = 1e5 # defines velocity unit of output (in cm/sec)

**Comment by andreufont** [comment]
Here is a similar histogram for another MP-Gadget simulation, similar cosmology to Sherwood, similar box size and resolution: L=90Mpc/h, N=1024, z=2.75

![Screen Shot 2019-06-06 at 15 36 06](https://user-images.githubusercontent.com/3873863/59041700-0b133180-8871-11e9-853f-83daaf55ef76.png)

Of course, note different in x-axis. It does look like the velocities are *very* different. Sherwood velocities peak at ~ 200 km/s, while MP-Gadget ones peak at ~ 40 km/s.

I did the histograms above calling Spectra.get_velocities(). I believe @Chris-Pedersen is redoing some of these tests now using directly BigFile, without going through fake_spectra.

**Comment by Chris-Pedersen** [comment]
Yes, I am currently working on making the equivalent plots directly from the snapshots.

**Comment by andreufont** [comment]
If the histograms by Chris show the same issue, the problem has to be in writing the BigFiles. 

If hte histograms by Crhis look good, then I think it is in fake_spectra reading BigFiles.

**Comment by Chris-Pedersen** [comment]
Comparison between a 512^3 L60 with 1024^3 L80 Sherwood sim, both at z=2, I see results consistent with Andreu's implying that the difference is in the bigfile velocities themselves. Perhaps some missing units on i/o? Important to bear in mind that currently restarts give very good agreement with non-restarted sim so if there is an error on output it must be corrected on reading bigfiles to restart.

![cdm_velocity_comparison](https://user-images.githubusercontent.com/16047009/59045068-4284dc80-8877-11e9-8de6-82f5481b3a63.png)
![gas_velocity_comparison](https://user-images.githubusercontent.com/16047009/59045073-444ea000-8877-11e9-9902-f466aecc3d2e.png)

**Comment by sbird** [comment]
Aha! Ok, then it is likely there is a bug outputting the velocities. Chris is totally right that it must be corrected on read as well as write. It is interesting that it changes with resolution. It looks about like a factor of 6-7 in Chris' plots. Let me take a look. If you get this in time, could you do me a huge favour and check whether the scale factor is redshift independent? The most obvious possible change is a missing sqrt(a) factor.

> `UnitLength_in_cm = 3.085678e21 # defines length unit of output (in cm/h)`
> `UnitMass_in_g = 1.989e43 # defines mass unit of output (in g/cm)`
> `UnitVelocity_in_cm_per_s = 1e5 # defines velocity unit of output (in cm/sec)`

That looks right!

Can you confirm (from the slurm output of your MP-GenIC run) that you have: UsePeculiarVelocity = 0 ?

**Comment by sbird** [comment]
This parameter will also be set in the snapshot header: please confirm that the bigfile header (a text file) has a line like this:
output/PART_000/Header (master)% cat attr-v2
[...]
UsePeculiarVelocity <i4 1 00000000 #HUMANE [ 0 ]
in case the bug is that this flag is being incorrectly set to 1.

**Comment by sbird** [comment]
I see it: in the Gadget-2 and Gadget-3 output routines the velocity is multiplied by:
	    for(k = 0; k < 3; k++)
	      fp[k] *= sqrt(a3inv);
on output, and divided on input. (IIRC, this was done to match Gadget-1's internal units.)

We do the same thing in our routine for reading the GenIC velocities but not in our snapshot output input routines. So the velocities in our snapshots are in a different format to the velocities in the ICs, by a factor of a^{-3/2} ~ 1/5.2 which is roughly the right factor to explain these discrepancies. I was not aware that the velocities output are not the same as Gadget-3, so I was correcting for the missing factor in fake_spectra.

This is...a bit of a mess. If we continue to output velocities in a different unit to vanilla Gadget by default there will be no end of trouble.

I propose:
a) A new header flag which reads "UseGadgetVelocities". If UseGadgetVelocities = 0 (or it is not present) we output the current velocities (comoving velocities). If UseGadgetVelocities = 1 we output the Gadget format velocities. UseGadgetVelocities = 1 by default.
b) I will teach fake_spectra to check for UseGadgetVelocities and apply the correction as necessary, so we will still be able to correctly analyze existing snapshots.

@rainwoodman Comments?

**Comment by sbird** [comment]
See PR https://github.com/MP-Gadget/MP-Gadget/pull/300 : please can you test that with this PR we generate velocities that are comparable to Gadget-3 and have a realistic beta.

**Comment by sbird** [comment]
I will also fix fake_spectra once you confirm this.

**Comment by andreufont** [comment]
Hi @sbird, @rainwoodman, thank you for looking at this.

My 2cts: there is nothing wrong with MP-Gadget and Gadget1-2-3 using different velocities, as long as this is well documented. fake_spectra should just be aware of that, and load the data accordingly.

Ideally we would have two discussions:
 - long term plan: what units to use, how to document it
- short term plan: how to hack fake_spectra to correct the input velocities, so that we can still us the simulations ran until today.

I'd be very happy to try a proposed hack for the second, short term discussion, since we have a lot of simulations that we'd like to recycle.

**Comment by Chris-Pedersen** [comment]
I've sent tests of #300 to the queue, DiRAC has been super slow recently though so will probably take a day or two. Will update as soon as they're done! Thanks a lot for looking at this @sbird .

**Comment by sbird** [comment]
I don't need a fake_spectra issue, I can just add the fix once you confirm this change works.

**Comment by andreufont** [comment]
Hi @sbird, a fix in fake_spectra since that would allow us to re-measure beta in the simulations we already have, without waiting for queues. These are pretty large sims!

**Comment by Chris-Pedersen** [comment]
Ok this certainly looks like the problem. When I rescale the velocities by a^{-3/2} on reading into fake_spectra we get really nice agreement with Sherwood:

![histo_velfixed](https://user-images.githubusercontent.com/16047009/59103745-9bac4900-8927-11e9-978c-3a1663b4bcde.png)

I've put a temporary hack into our fake_spectra installs so we can keep working with our simulations until there's a fix on master.

I'll also add a plot of the bias with the rescaling to confirm the beta lines up with Sherwood.

**Comment by sbird** [comment]
@Chris-Pedersen  Thanks for the quick plots! This is great. Ok, I will fix fake_spectra in the master branch (which is easy). I would like @rainwoodman  to comment on fixing this in Gadget. 

It is true that the Gadget default unit velocities don't make a lot of sense, so from the perspective of a new user it is best to leave MP-Gadget as it is now. My worry is that it will break existing codes, but maybe since we have a new file format anyway that's fine: we should just add documentation about this and teach the format conversion script to multiply by the right factor.

**Comment by sbird** [comment]
However, if we do that I think we should make clear somewhere that the initial conditions and snapshots have different velocity units, and maybe change MP-GenIC so that by default it uses the same physical km/s velocities as MP-Gadget. @rainwoodman ?

**Comment by rainwoodman** [comment]
I think we shall use peculiar velocity everywhere; that's the unit most relevant in cosmology. Let's get rid of that a^(1/2) factor in MP-GenIC.

**Comment by Chris-Pedersen** [comment]
The DiRAC queues are really bad so my 512**3 test of your fixvel branch is still in the queue. But in the meantime I've regenerated the bias plots after rescaling the velocities on input to fake_spectra and the beta looks great now!

![hallelujah](https://user-images.githubusercontent.com/16047009/59197752-f93fd000-8b89-11e9-92f8-39670bf8c003.png)

Will update once the fixvel sim is finished.

**Comment by sbird** [comment]
Perfect! Thanks Chris! I think you can drop the fixvel sim as we have decided not to alter MP-Gadget's output. We will probably set UsePeculiarVelocity = 1 by default, which means the code will use the same velocities for IC and snapshots, and these velocities will just be the peculiar velocities.

**Comment by sbird** [comment]
If you could give the current master of fake_spectra a quick test to ensure it matches the output you have now, that would be appreciated!

**Comment by sbird** [comment]
The current PR is: https://github.com/MP-Gadget/MP-Gadget/pull/301
Together with the fake_spectra fix, the fixes to the conversion script should ensure that fake_spectra produces the same output when run on a bigfile or after converting a bigfile to hdf5

**Comment by Chris-Pedersen** [comment]
Hi @sbird , testing your fake_spectra master now, just a note that in line 348 in fake_spectra/abstractsnapshot.py, the header attr should be `"UsePeculiarVelocity"` instead of `"UsePeculiarVelocities"`. Will update with plots once the new spectra are generated!

**Comment by Chris-Pedersen** [comment]
Generating a fresh set of skewers using your master I get bias and beta consistent with my hack above:

![simeon_fake_fix](https://user-images.githubusercontent.com/16047009/59313053-45ccfd80-8ca7-11e9-9914-7a0a77512822.png)

**Comment by sbird** [comment]
> Hi @sbird , testing your fake_spectra master now, just a note that in line 348 in fake_spectra/abstractsnapshot.py, the header attr should be `"UsePeculiarVelocity"` instead of `"UsePeculiarVelocities"`. Will update with plots once the new spectra are generated!

Indeed! Thank you! Fixed now.

**Comment by sbird** [comment]
Ok a new fake_spectra release is tagged. This should work now, closing. Thanks for the tests!
