### ISSUE TITLE
Bump in Lyaf P1D at high k and high z

### ISSUE THREAD

**Issue by Chris-Pedersen** [MP-Gadget/MP-Gadget#303]
We noticed we see a smooth spike in power in the P1D calculated using fake_spectra. This only appears at high k and at high z, but we're struggling to explain it and don't think it should be there physically.

These are with GLASS ICs off on two different 512 L~45 Mpc/h boxes

![p1d_newversion](https://user-images.githubusercontent.com/16047009/59886103-a4842c80-93b5-11e9-8a1d-1172f19cbc2e.png)
![p1d_oldversion](https://user-images.githubusercontent.com/16047009/59886107-a6e68680-93b5-11e9-8cab-5ad83fbe37ac.png)

and I've checked that changing the skewer resolution has no effect on this. Do you have any idea what could be going on?

**Comment by sbird** [comment]
That looks like a particle resolution effect to me. That simulation is *very* not resolved at those k and z values. Resolving the forest is much harder at high z. See Bolton & Becker 2010.

**Comment by Chris-Pedersen** [comment]
I think you're right, we ran some much higher res sims and it goes away. Thanks, closing this!
