### ISSUE TITLE
MP-Gadget snapshots on tape

### ISSUE THREAD

**Issue by Chris-Pedersen** [MP-Gadget/MP-Gadget#307]
We are looking to store some large simulations on tape, and after some discussion with the relevant admins they advise that we compress the snapshots into as few a files as possible beforehand. This might be an issue when using bigfiles due to the large file number. Is this something either Yu or Simeon have attempted before? One option would be to wrap the bigfiles for each snapshot into a tarball, can you forsee any problems with that?

**Comment by sbird** [comment]
Nope, it should be fine to wrap them in a tarball. Just don't compress them. The data is immutable once written.
