### ISSUE TITLE
Code Review Starter

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#310]
We should have a simple guideline to on board new code reviewers.

I did some quick research on this and found a few links:

1. A general guide:

https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/

2. This link from MIT has some tactic level guidelines:

http://web.mit.edu/6.005/www/fa15/classes/04-code-review/

**Comment by sbird** [comment]
Added links to readme.
