### ISSUE TITLE
Stop using git submodule.

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#370]
While submodule provides a way to checkout any specific version, it is not that convenient to always do the bootstrap script; and it is always a bit confusing when to do update and when to do init.

Alternatively, we can embedded the source code of other dependencies (other than pfft, which downloads a source code). 

We can manually 'down-integration' the code into MP-Gadget to the latest version, with a script like this: https://github.com/rainwoodman/fastpm/blob/master/depends/kdcount/down-integrate.sh

We should be able to add a flag to pick any commit, when the use case eventually rises.

**Comment by sbird** [comment]
I think I don't want to do this right now. The only submodule left is bigfile and it is too useful to have the bigfile tests and support scripts handy.
