### ISSUE TITLE
futex vs spinlocks

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#383]
I was looking at [Futex](https://lwn.net/Articles/360699/), because people usually say doing spinlock in userspace is more often wrong than not.

Our main reason for using spinlocks is that spinlocks are cheap in storage. It needs exactly one int.

By looking at the canonical examples futex, seems to be use only a single int storage, too. 
However it is the figure on the lwn article that made me worrying. My reading of the story is that the linux syscall tracks another integer via a hash table for the internal state of the futex, deciding when to wake up whom. 

It is not clear if this mechanism scales up to a few hundred million futex objects. Although our number of active threads is much lower. 

I remember when I was measuring the contention it was not very often that two threads race on the same spinlock ( << 10% of races), and we never oversubscribe the cores, so I suspect even if we switch to use Futex there won't be much gain.

And I was taken to the futex article from this thread:

https://www.realworldtech.com/forum/?threadid=189711&curpostid=189723

**Comment by sbird** [comment]
Indeed - I read that thread as well! PR #382 was the result. We are running on a dedicated host and never need to be scheduled out, so we are probably not going to benefit much, I agree. But sometimes we do use hyperthreading, so maybe I'm wrong. I could try switching to pthread_mutex, which uses futexes internally. The tree build algorithm really wants to use pthread_rwloc_t.

One other reason we use spinlocks is that they are very cheap to initialise. We have to init a spinlock for every data member every timestep, even if few data members are active. At one point I tried switching to omp locks and the initialisation overhead on intel was so large that the code was a factor of two slower.

For the particle locks, we are actually very close to being able to express it with omp atomics. All we need is:

atomic update
x = max(x, y)

(which interestingly enough already exists in fortran).

There seems to be https://en.cppreference.com/w/c/atomic/atomic_compare_exchange in C11 but I am unsure about the implications of using it within an openmp block.

What do you think? We would have to test carefully.

**Comment by sbird** [comment]
I just tried the pthread rwlock version of the tree build algorithm and it is indeed much slower (factor of 3) than the current code on the test. Not sure how much is the initialisation overhead.

**Comment by rainwoodman** [comment]
hmm. About the atomics -- don't we need to wait -- are you sure there is no data dependency protected by the locks?

I don't think openmp can play any magic to break atomic / compare_exchange -- though if the CPU doesn't natively support the width then it gets very tricky.

pthread_mutex is 48 types in size. I think rwloc is also kind of large.

Why can't we reuse the lock objects? Every time step ensures all spinlocks are unlocked at the end. If every lock is initialized to MaxPart in P, then we can reuse them.

**Comment by sbird** [comment]
Not really - with the exception of the fof code, which is run infrequently enough that any lock will do, our particle spinlocks are really just protecting compare/swap pairs right now.

I am more worried about our forcetree spinlocks, which do protect real data dependent code.

These are the locks whose initialisation overhead matters, because tree is run so often and so easily dominates the timestep time. We could reuse those lock objects if we wanted, but it is a little tricky because we might have to increase the number of force nodes.

**Comment by rainwoodman** [comment]
I think we dont have to store the locks inside tree nodes? Does that help?

**Comment by sbird** [comment]
We already store them separately. I am saying that either we allocate enough memory for locks below the domain, in which case we cannot easily increase the number of tree nodes without freeing domain, or we allocate them above domain, in which case we cannot reuse them easily. We could allocate them above domain and reuse them only every long timestep, but it seems a lot of effort for small gain...

**Comment by sbird** [comment]
I removed the compare/swap locks but the forecetree building locks I think have to stay: they are protecting a memory area wide enough that it would be difficult to make accesses atomic.
