### ISSUE TITLE
Restarts rewriting restarted snapshot

### ISSUE THREAD

**Issue by Chris-Pedersen** [MP-Gadget/MP-Gadget#412]
Hi! On some of my restarts, the very first thing the code does is write another snapshot at the same redshift that it has just loaded the particle data from. [Here is an output file](https://github.com/MP-Gadget/MP-Gadget/files/4359838/restart_rewrite.txt) - in this case the simulation is restarted at snapshot 9, z=2.25. It straight away writes snapshot 10, also at z=2.25.

[Here is an output file](https://github.com/MP-Gadget/MP-Gadget/files/4359839/restart_norewrite.txt) for a simulation where the snapshot wasn't rewritten - I can't see any difference in the setups that would lead to different behaviour.

**Comment by sbird** [comment]
Could you confirm this still occurs with master? In general we will only fix bugs in the master version.

**Comment by sbird** [comment]
I believe this has been fixed in master, closing.
