### ISSUE TITLE
CritDensThresh vs PhysDensThresh

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#44]
@sbird 

I thought they are the same but they are not. The logic here is a bit twisted. Apparently PhysDensThresh sets the two phase media model threshold, and CritDensThresh sets start formation threshold?

What does CritDensThresh = 57.7 mean?

**Comment by rainwoodman** [comment]
I think we probably want the OWL sfr module in a separate, enableable module. How different is it really from SH03?

**Comment by sbird** [comment]
Not much at all. It just drops some complexities, like the beta return fraction, that don't really make a difference. If you are not restarting we should leave it.
