### ISSUE TITLE
Proximity aware allocation.

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#456]
This may speed up the cull_node() call by putting nodes nearby to nearby memory locations.

```
class ProximityAwareAllocator:
  int elsize;
  void* Allocate(int64_t key); // allocate from the bucket. If full, do deterministic retries.
  private:
    int KeyToBucketID(int64_t key); // preserves the proximity of keys.
    void (* buckets)[N_buckets].
    int tops[N_buckets];
    void * base_ptr;
```

Problem could be that the locking of Allocate is too big that tree bulid becomes slow. But we do more tree walks this may still end up as a gain.

**Comment by sbird** [comment]
This reminded me to check the profiling data. Here is the top of the dm-only example on 24 threads, 1 MPI:

Samples: 27M of event 'cycles:u', Event count (approx.): 26866932029802
Overhead  Command    Shared Object                  Symbol
  23.49%  MP-Gadget  libgomp.so.1.0.0               [.] gomp_barrier_wait_end        ◆
  10.64%  MP-Gadget  MP-Gadget                      [.] fftw_cpy2d                   ▒
  10.19%  MP-Gadget  MP-Gadget                      [.] apply_accn_to_output         ▒
   9.39%  MP-Gadget  MP-Gadget                      [.] force_treeev_shortrange      ▒
   8.52%  MP-Gadget  MP-Gadget                      [.] grav_apply_short_range_window▒
   4.96%  MP-Gadget  MP-Gadget                      [.] n1_12                        ▒
   3.27%  MP-Gadget  libgomp.so.1.0.0               [.] gomp_team_barrier_wait_end   ▒
   3.09%  MP-Gadget  MP-Gadget                      [.] fftw_transpose               ▒
   1.95%  MP-Gadget  MP-Gadget                      [.] t2_32                        ▒
   1.92%  MP-Gadget  libc-2.31.so                   [.] __memmove_avx_unaligned_erms ▒
   1.78%  MP-Gadget  MP-Gadget                      [.] r2cf_2                       ▒
   1.72%  MP-Gadget  MP-Gadget                      [.] hc2cb_16                     ▒
   1.41%  MP-Gadget  MP-Gadget                      [.] to_region                    ▒
   1.19%  MP-Gadget  MP-Gadget                      [.] pm_apply_transfer_function._o▒
   0.80%  MP-Gadget  MP-Gadget                      [.] apply_half_kick._omp_fn.0    ▒
   0.80%  MP-Gadget  MP-Gadget                      [.] order_by_type_and_key        ▒
   0.68%  MP-Gadget  libm-2.31.so                   [.] 0x0000000000080282           ▒
   0.65%  MP-Gadget  MP-Gadget                      [.] potential_transfer           ▒
   0.60%  MP-Gadget  MP-Gadget                      [.] to_pfft                      ▒
   0.55%  MP-Gadget  MP-Gadget                      [.] do_the_long_range_kick._omp_f▒
   0.51%  MP-Gadget  MP-Gadget                      [.] r2cb_16                      ▒
   0.51%  MP-Gadget  MP-Gadget                      [.] pm_iterate._omp_fn.0         ▒
   0.45%  MP-Gadget  MP-Gadget                      [.] put_particle_to_mesh         ▒
   0.42%  MP-Gadget  MP-Gadget                      [.] drift_all_particles._omp_fn.0▒
   0.38%  MP-Gadget  MP-Gadget                      [.] readout_force_x              ▒
   0.37%  MP-Gadget  MP-Gadget                      [.] readout_force_y              ▒
   0.36%  MP-Gadget  MP-Gadget                      [.] readout_force_z              ▒
   0.36%  MP-Gadget  MP-Gadget                      [.] readout_potential            ▒

Hot instructions in apply_accn_to_output are (I think first is a commonly failed branch prediction?):
      │     if(r >= h)                                                              ▒
  0.00 │       vcomisd      %xmm0,%xmm6                                              ▒
       │     {                                                                       ▒
  4.34 │       vmovsd       %xmm3,%xmm3,%xmm1                                        ◆
       │     if(r >= h)                                                              ▒
  0.08 │     ↓ jb           d0                                                       ▒
       │     {                                                                       ▒
       │     fac = mass / (r2 * r);                                                  ▒
  3.59 │       vmulsd       %xmm6,%xmm4,%xmm4                                        ▒
  0.06 │       vdivsd       %xmm4,%xmm2,%xmm4                                        ▒
       │     facpot = -mass / r;                                                     ▒
 29.19 │       vxorpd       0x1340ba(%rip),%xmm2,%xmm2        # 1753d0 <_IO_stdin_use▒
  0.01 │       vdivsd       %xmm6,%xmm2,%xmm2                                        ▒
       │     fac = mass / (r2 * r);                                                  ▒
  1.62 │       vmovsd       %xmm4,0x10(%rsp)                                         ▒
       │     facpot = -mass / r;                                                     ▒
  1.77 │       vmovsd       %xmm2,0x8(%rsp)                                          ▒
       │     }                                                                       ▒

sqrt near the top:
       │                                                                             ▒
       │     const double r = sqrt(r2);                                              ▒
  2.27 │       vsqrtsd      %xmm4,%xmm4,%xmm6                                        ▒
       │     {                                                                       ▒
 22.79 │       mov          %rdi,%rbx                                                ▒
  0.01 │       mov          %rsi,%rbp                                                ▒
  0.00 │       mov          %fs:0x28,%rax                                            ▒
  0.02 │       mov          %rax,0x18(%rsp)                                          ▒
  0.00 │       xor          %eax,%eax                                                ▒
       │                                                                             ▒

And in force_treeev_shortrange:
       │     if(r2 > rcut2)                                                          ▒
  4.82 │       vcomisd     0x30(%rsp),%xmm0                                          ▒
  4.59 │    ┌──jbe         21f                                                       ▒

I think this one is moving P into cache:
      │     dx[j] = NEAREST(P[pp].Pos[j] - inpos[j], BoxSize);                      ▒
  0.75 │3b0:   vaddsd      %xmm5,%xmm1,%xmm0                                         ▒
  0.11 │       vcmpltsd    0x20(%rsp),%xmm1,%xmm2                                    ▒
  0.01 │       vblendvpd   %xmm2,%xmm0,%xmm1,%xmm1                                   ▒
  2.31 │3c1:   vmovsd      %xmm1,0x70(%rsp)                                          ▒
  0.40 │       vmovsd      0x10(%rax),%xmm2                                          ▒
  0.21 │       vsubsd      0x8(%r12),%xmm2,%xmm2                                     ▒
  0.27 │       vcomisd     %xmm4,%xmm2                                               ▒
  0.33 │     ↓ ja          5c0                                                       ◆
  0.32 │       vaddsd      %xmm5,%xmm2,%xmm0                                         ▒
  0.02 │       vcmpltsd    0x20(%rsp),%xmm2,%xmm6                                    ▒
  2.19 │       vblendvpd   %xmm6,%xmm0,%xmm2,%xmm2                                   ▒
  0.32 │3ee:   vmovsd      %xmm2,0x78(%rsp)                                          ▒
  0.29 │       vmovsd      0x18(%rax),%xmm0                                          ▒
  0.64 │       vsubsd      0x10(%r12),%xmm0,%xmm0                                    ▒
  0.16 │       vcomisd     %xmm4,%xmm0                                               ▒
  0.57 │     ↓ ja          5b0                                                       ▒
  0.50 │       vaddsd      %xmm5,%xmm0,%xmm6                                         ▒
  2.16 │       vcmpltsd    0x20(%rsp),%xmm0,%xmm7                                    ▒
  0.12 │       vblendvpd   %xmm7,%xmm6,%xmm0,%xmm0                                   ▒

Not sure why? Loading input, perhaps?
       │     double h = input->Soft;                                                 ▒
  4.55 │       vmovsd      0x38(%r12),%xmm1                                          ▒

**Comment by sbird** [comment]
From the hydro example:
  25.12%  MP-Gadget  MP-Gadget               [.] treewalk_visit_ngbiter              ◆
  14.76%  MP-Gadget  MP-Gadget               [.] force_treeev_shortrange             ▒
   8.36%  MP-Gadget  libgomp.so.1.0.0        [.] gomp_barrier_wait_end               ▒
   7.83%  MP-Gadget  MP-Gadget               [.] apply_accn_to_output                ▒
   7.61%  MP-Gadget  libgomp.so.1.0.0        [.] gomp_team_barrier_wait_end          ▒
   6.50%  MP-Gadget  MP-Gadget               [.] grav_apply_short_range_window       ▒
   3.65%  MP-Gadget  MP-Gadget               [.] hydro_ngbiter                       ▒
   2.72%  MP-Gadget  MP-Gadget               [.] density_ngbiter                     ▒
   1.64%  MP-Gadget  MP-Gadget               [.] scipy_optimize_fixed_point          ▒
   1.37%  MP-Gadget  MP-Gadget               [.] fftw_cpy2d                          ▒
   1.00%  MP-Gadget  MP-Gadget               [.] dwk_qs                              ▒
   0.90%  MP-Gadget  MP-Gadget               [.] winds_is_particle_decoupled         ▒
   0.86%  MP-Gadget  MP-Gadget               [.] density._omp_fn.0                   ▒
   0.78%  MP-Gadget  MP-Gadget               [.] interp_eval                         ▒
   0.77%  MP-Gadget  MP-Gadget               [.] drift_all_particles._omp_fn.0       ▒
   0.72%  MP-Gadget  MP-Gadget               [.] n1_12                               ▒
   0.65%  MP-Gadget  MP-Gadget               [.] wk_qs                               ▒
   0.62%  MP-Gadget  MP-Gadget               [.] get_heatingcooling_rate             ▒
   0.60%  MP-Gadget  MP-Gadget               [.] force_tree_create_nodes._omp_fn.0   ▒
   0.58%  MP-Gadget  MP-Gadget               [.] peano_hilbert_key                   ▒

Hot instructions in treewalk_visit_ngbiter:
       │     if(iter->symmetric == NGB_TREEFIND_SYMMETRIC) {                         ▒
  6.93 │       mov         (%r14),%r10d                                              ▒
  0.06 │       vmovsd      0x8(%r14),%xmm0                                           ▒
       │     dist = DMAX(current->mom.hmax, iter->Hsml) + 0.5 * current->len;        ▒
  0.08 │       vmulsd      %xmm4,%xmm12,%xmm2                                        ▒
       │     if(iter->symmetric == NGB_TREEFIND_SYMMETRIC) {                         ▒
  4.35 │       test        %r10d,%r10d                                               ▒
  0.02 │     ↓ je          4a0                                                       ▒
       │     dist = iter->Hsml + 0.5 * current->len;                                 ▒
 
This one is the impossible-to-predict sibling/nextnode jump:
       │     for (i = 0; i < current->s.noccupied; i++) {                            ▒
  0.03 │4e0:   mov         0x84(%r12),%edi                                           ▒
  0.60 │       test        %edi,%edi                                                 ▒
  0.04 │     ↓ jle         520                                                       ▒
  0.00 │       mov         0x28(%rbx),%rax                                           ▒
  0.06 │       movslq      %r15d,%rsi                                                ▒
  0.00 │       lea         0x1(%r15),%r10d                                           ▒
  0.41 │       lea         (%rax,%rsi,4),%rdi                                        ▒
       │     lv->ngblist[numcand++] = suns[i];                                       ▒
  0.02 │       xor         %eax,%eax                                                 ▒
  0.01 │       nop                                                                   ▒
  0.01 │500:   mov         0x58(%r12,%rax,4),%esi                                    ▒
  2.21 │       lea         (%r10,%rax,1),%r15d                                       ▒
  0.03 │       mov         %esi,(%rdi,%rax,4)                                        ▒
       │     for (i = 0; i < current->s.noccupied; i++) {                            ▒
  0.31 │       inc         %rax                                                      ▒
  0.03 │       cmp         %eax,0x84(%r12)                                           ▒
  0.60 │     ↑ jg          500                                                       ▒
  0.00 │       nop                                                                   ▒
       │     no = current->sibling;                                                  ▒
  1.17 │520:   mov         (%r12),%r10d                                              ▒
       │     continue;                                                               ◆
  6.14 │     ↑ jmpq        2af                                                       ▒

This one is the latency loading P[other] into cache:
      │     for(numngb = 0; numngb < numcand; numngb ++) {                          ▒
  0.73 │310:   add         $0x4,%rbx                                                 ▒
  3.52 │       cmp         %r12,%rbx                                                 ▒
  0.80 │     ↓ je          6a0                                                       ◆
       │     int other = lv->ngblist[numngb];                                        ▒
  0.00 │31d:   mov         0x28(%rax),%rdx                                           ▒
  0.87 │       movslq      (%rdx,%rbx,1),%rdx                                        ▒
  1.13 │       mov         %rdx,%rcx                                                 ▒
       │     if(P[other].IsGarbage)                                                  ▒
  0.09 │       imul        $0x98,%rdx,%rdx                                           ▒
  0.62 │       add         (%r10),%rdx                                               ▒
  0.30 │       movzbl      0x24(%rdx),%esi                                           ▒
 10.58 │       test        $0x10,%sil                                                ▒
  0.11 │     ↑ jne         310                                                       ▒
       │     if(!((1<<P[other].Type) & iter->mask))                                  ▒
  0.00 │       mov         0x4(%r13),%r8d                                            ▒
  0.15 │       and         $0xf,%esi                                                 ▒
  0.13 │       bt          %esi,%r8d                                                 ▒
  0.11 │     ↑ jae         310                                                       ▒
       │     if(lv->tw->type == TREEWALK_SPLIT && !(BINMASK(P[other].TimeBin) & lv->t▒
  0.43 │       mov         (%rax),%r8                                                ▒
  2.00 │       cmpl        $0x2,0x18(%r8)                                            ▒

And the other top hits are the same as the gravity forcetree.

**Comment by sbird** [comment]
And here is the output of perf stat:
[spb41]MP-Gadget/examples/hydro (master)% nice -n 19 perf stat -d ../../gadget/MP-Gadget paramfile.gadget 2>&1 1>/dev/null
^C../../gadget/MP-Gadget: Interrupt

 Performance counter stats for '../../gadget/MP-Gadget paramfile.gadget':

      8,007,488.78 msec task-clock                #   22.792 CPUs utilized          
           102,969      context-switches          #    0.013 K/sec                  
               287      cpu-migrations            #    0.000 K/sec                  
        29,183,149      page-faults               #    0.004 M/sec                  
32,110,785,467,446      cycles                    #    4.010 GHz                      (62.50%)
 2,074,826,798,557      stalled-cycles-frontend   #    6.46% frontend cycles idle     (62.50%)
 2,674,226,724,832      stalled-cycles-backend    #    8.33% backend cycles idle      (62.50%)
26,199,156,610,641      instructions              #    0.82  insn per cycle         
                                                  #    0.10  stalled cycles per insn  (62.50%)
 4,556,408,032,998      branches                  #  569.018 M/sec                    (62.50%)
   144,405,714,441      branch-misses             #    3.17% of all branches          (62.50%)
11,850,612,433,805      L1-dcache-loads           # 1479.941 M/sec                    (62.50%)
   664,970,610,073      L1-dcache-load-misses     #    5.61% of all L1-dcache hits    (62.50%)
   <not supported>      LLC-loads                                                   
   <not supported>      LLC-load-misses                                             

     351.332046759 seconds time elapsed

    7857.056418000 seconds user
     106.343956000 seconds sys


nice -n 19 perf stat -d ../../gadget/MP-Gadget paramfile.gadget 2>&1 >   7857.07s user 106.35s system 2266% cpu 5:51.40 total

This is on a 12 core AMD Zen 2: the dcache load miss is alarming

**Comment by sbird** [comment]
This is on my (older) Intel:
[spb41]MP-Gadget/examples/hydro (master)% nice -n 19 perf stat -d ../../gadget/MP-Gadget paramfile.gadget 2>&1 1>/dev/null
^C../../gadget/MP-Gadget: Interrupt

 Performance counter stats for '../../gadget/MP-Gadget paramfile.gadget':

        776,677.05 msec task-clock:u              #    7.008 CPUs utilized          
                 0      context-switches:u        #    0.000 K/sec                  
                 0      cpu-migrations:u          #    0.000 K/sec                  
         3,549,522      page-faults:u             #    0.005 M/sec                  
 2,891,806,497,843      cycles:u                  #    3.723 GHz                      (45.82%)
 2,312,150,337,134      instructions:u            #    0.80  insn per cycle           (58.32%)
   415,358,793,604      branches:u                #  534.790 M/sec                    (58.31%)
    12,269,937,633      branch-misses:u           #    2.95% of all branches          (57.87%)
   678,360,218,025      L1-dcache-loads:u         #  873.413 M/sec                    (36.20%)
    50,995,747,965      L1-dcache-load-misses:u   #    7.52% of all L1-dcache hits    (29.51%)
    18,340,383,192      LLC-loads:u               #   23.614 M/sec                    (26.96%)
     1,722,355,276      LLC-load-misses:u         #    9.39% of all LL-cache hits     (35.09%)

     110.830432067 seconds time elapsed

     763.906169000 seconds user
       8.941811000 seconds sys


nice -n 19 perf stat -d ../../gadget/MP-Gadget paramfile.gadget 2>&1 >   763.92s user 8.95s system 697% cpu 1:50.88 total

**Comment by rainwoodman** [comment]
Looks like we the mem loads from both P and *current are having a lot of latency, even though P is already peano ordered.

I realized proximity doesn't lead to a reduction of cache misses. If our access is out of order, (e.g. fully reversed) then would we still as many cache misses?

About the cache miss rate, what targets shall we aim for? In other terms, why is a < 10% cache miss concerning?

**Comment by sbird** [comment]
This is true - it might be if we have to operate on a 3D dataset which is > cache size then a high cache miss rate is perhaps unavoidable. Maybe we should instead try to implement MFM to reduce the number of neighbours needed for hydro and FMM to make the gravity O(N)?

**Comment by rainwoodman** [comment]
The data of a few hundred particles per thread should still fit into the cache -- 12 * 200 (bytes per particle) * 200(particles) = 400 KB.
For hydro (ngbiter on P), if the pair is (i, j) and i is the primary particle, then the number of cache misses would be proportional to the fraction of neighbours are no longer neighbours after an i-increment. aka the difference of {j}_i and {j}_i+1.
This is probably the value of peano sorting -- to ensure the proximity of i, and proximity of j is irrelevant. 

Next, gravity. I think we touch many more tree nodes than hydro, as the support of the short-range gravity is longer in dense areas than the smoothing length of hydro. This may be why we are out of cache?

Do you have a sense how many tree nodes is touched for computing the force of a single particle? Trimming and packing fields such that we can fit some_weighted_mean_N_nodes_per_particle * (struct of hot node fields) into L1 might give us a drastic speed gain if that's the case, as the (i) of gravity is already peano sorted.

I suspect this will be a problem for FMM as well, as in then end the short-range gravity will likely need similar amount of floating numbers to arrive to a similar accuracy.

**Comment by sbird** [comment]
That sounds very likely - I don't know how many tree nodes we touch for particle forces, offhand. I think it changes dramatically depending on the setup, but I agree that moving Pos and Mass into some hot array could be very helpful. Especially if we made Mass be a lookup into a type table (for CDM), instead of a per-particle attribute.

**Comment by sbird** [comment]
Pos though is a very large array: we could need a lot of storage for this. But I suppose if it is only for gravity it is ok.

**Comment by sbird** [comment]
hmm, we need Type as well.

**Comment by rainwoodman** [comment]
24 (pos) + 4 (mass) + 4(type and etc) = 32 bytes per particle. 

What about the nodes? An easy way to improve the caching is to convert the entire struct to column based, then we don't worry which is hot which is cold...

**Comment by sbird** [comment]
I didn't move the node struct to column based because it messes with the current realloc() to shrink it down to only what is necessary.

**Comment by sbird** [comment]
I tried something like this in PR #465 , storing the particle Type in the node structure. This should be the best possible effect from cache locality because the node is already hot and because storing the Type avoids loading on average 50% of the particles in the hydro treewalk. It had marginal effects.

**Comment by sbird** [comment]
Closing because mostly implemented.
