### ISSUE TITLE
deficit error in mpsort at large ranks

### ISSUE THREAD

**Issue by sbird** [MP-Gadget/MP-Gadget#462]
We have the following crash on frontera, constant on 8000 ranks, rarely on 4000 ranks. 

I suspect this of being due to some icc mis-optimization combined with flaky MPI and am about to do some defensive programming in mpsort_mpi. 

[ 062854.68 ] ERROR: Task 7000: [ 062854.96 ] ERROR: Task 7501: [ 062854.89 ] ERROR: Task 6500: [ 062854.68 ] ERROR: Task 7001: serious bug: more items than there should be: deficit=-45639756
[ 062854.99 ] ERROR: Task 6194: [ 062855.09 ] ERROR: Task 7034: [ 062854.77 ] ERROR: Task 7502: [ 062855.07 ] ERROR: Task 6503: [ 062854.60 ] ERROR: Task 6320: [ 062854.89 ] ERROR: Task 7098: [ 062854.76 ] ERROR: Task 7535: [ 062854.60 ] ERROR: Task 6350: serious bug: more items than there should be: deficit=-79452430
[ 062854.32 ] ERROR: Task 7410: [ 062854.71 ] ERROR: Task 7566: serious bug: more items than there should be: deficit=-18647945
[ 062854.83 ] ERROR: Task 6380: [ 062854.46 ] ERROR: Task 7470: [ 062854.87 ] ERROR: Task 7598: serious bug: more items than there should be: deficit=-17485474
[ 062854.94 ] ERROR: Task 6410: serious bug: more items than there should be: deficit=-76454013
serious bug: more items than there should be: deficit=-45649271
[ 062854.79 ] ERROR: Task 7630: [ 062854.26 ] ERROR: Task 6534: [ 062854.73 ] ERROR: Task 6440: [ 062854.96 ] ERROR: Task 7003: [ 062854.70 ] ERROR: Task 7662: [ 062854.41 ] ERROR: Task 6566: [ 062854.62 ] ERROR: Task 6470: serious bug: more items than there should be: deficit=-73083986
[ 062854.95 ] ERROR: Task 7066: [ 062854.85 ] ERROR: Task 7758: [ 062855.02 ] ERROR: Task 6630: serious bug: more items than there should be: deficit=-63822934
[ 062854.31 ] ERROR: Task 6159: [ 062854.64 ] ERROR: Task 7130: [ 062854.61 ] ERROR: Task 7850: [ 062854.46 ] ERROR: Task 6662: serious bug: more items than there should be: deficit=-61758143
[ 062854.71 ] ERROR: Task 6162: [ 062854.85 ] ERROR: Task 7168: serious bug: more items than there should be: deficit=-37010738
[ 062854.64 ] ERROR: Task 7910: [ 062854.63 ] ERROR: Task 6694: serious bug: more items than there should be: deficit=-59991944
[ 062855.00 ] ERROR: Task 6195: serious bug: more items than there should be: deficit=-85818448
[ 062854.76 ] ERROR: Task 7197: [ 062854.50 ] ERROR: Task 7941: [ 062854.38 ] ERROR: Task 6727: [ 062854.85 ] ERROR: Task 6227: [ 062854.82 ] ERROR: Task 7226: [ 062854.66 ] ERROR: Task 7970: [ 062854.75 ] ERROR: Task 6759: [ 062854.84 ] ERROR: Task 6258: serious bug: more items than there should be: de

**Comment by yueyingn** [comment]
The crash is constant on 16000 ranks, and rare on 8000 ranks.

**Comment by rainwoodman** [comment]
Could be related to reduction of long integers overflown?

**Comment by sbird** [comment]
Perhaps - do you see any? We are using ptrdiff_t for everything in this code. 
signed integer overflow is undefined so it doesn't need to actually happen, just be possible and get hit by icc's optimizer. 
I also wondered if the stack was overflowing.

**Comment by sbird** [comment]
I thought at one point that our use of a custom MPI_Datatype was confusing the MPI library, but I don't think that should be the case because any half-decent compiler should optimize that conditional at compile time.

**Comment by sbird** [comment]
Looking this over, I can see no integer overflows. I think this is the problem that impi sometimes exceeds some timeout and returns zero. Can we do a recompile for impi 19.1.1 and see if it goes away?

**Comment by rainwoodman** [comment]
You mean it returns 0 without terminating the application?

Perhaps try to run with a lower optimization level? I wonder if we shall
see if the problem is reproduced using bench-mpi.c.
Could it also be that we have incompatible functions (mp-mpiu.c) and LTO is
picking up a wrong object?

**Comment by rainwoodman** [comment]
I noticed the time stamp is > 60000. Is this the first time doing a sorting like this during the run?

**Comment by sbird** [comment]
I'm not sure that we can reproduce this anymore, because we need 4000 nodes to get it reliably and the large day is over. 

> I noticed the time stamp is > 60000. Is this the first time doing a sorting like this during the run?

The crash I saw at 4000 ranks was during FOF, which is the large radix test case. This will happen every time a snapshot is written. The crash at 8000 ranks was during the initial ID sort.

**Comment by sbird** [comment]
We have LTO turned off because icc crashed with an internal error

**Comment by sbird** [comment]
Yu, could you take a look at the travis failure for #463 ? It looks like one of nbodykit's dependencies broke.

**Comment by rainwoodman** [comment]
Yes. I was aware of that. A new release of nbodykit was made (0.3.15) --
retry the travis build?

Perhaps run with:
MPSORT_DISABLE_GATHER_SORT to avoid the aggregation?

**Comment by rainwoodman** [comment]
Let's also print the value of i near the error message:

https://github.com/MP-Gadget/MP-Gadget/blob/master/libgadget/utils/mpsort.c#L1381
https://github.com/MP-Gadget/MP-Gadget/blob/master/libgadget/utils/mpsort.c#L1376
Perhaps we shall dump the full variables?

**Comment by sbird** [comment]
Like this? https://github.com/MP-Gadget/MP-Gadget/pull/463/commits/218ec26ac82c60b6b56c5ef57c66d46f488670b5

If you are ok with that PR I can merge it and we will see what happens next time we get the bug

**Comment by sbird** [comment]
We ran on the full machine for a day without seeing this, so I think it's fixed now.
