### ISSUE TITLE
convert may need a lot of memory

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#466]
Due to this line, the memory is O(Ntot) instead of O(Nperfile):

https://github.com/MP-Gadget/MP-Gadget/blob/c4e98ae5dbe8b736383004701b73435808cb4703/tools/convert_from_gadget_1.py#L77

**Comment by sbird** [comment]
Doesn't dask automatically take care of disc caching? I was able to run it on my desktop with a large simulation. The result should be only 1-2 elements.

**Comment by rainwoodman** [comment]
Right. This only computes the locations of duplicated IDs, which is small.
