### ISSUE TITLE
Suggest: renaming the script to convert_bigfile_gadget_hdf5.py

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#469]
https://github.com/MP-Gadget/MP-Gadget/blob/b459f6954e70ce85302da23e105eef35c702d984/tools/convert_bigfile_gadget_format3.py#L2

We were looking for a converter from gadget hdf5 to MP-Gadget, and I narrowly missed this script, for there was no HDF5 in the file name.

**Comment by sbird** [comment]
hah, that is fair. Do you want to do it?
