### ISSUE TITLE
Running with non-standard dark energy (i.e. w=/=-1)

### ISSUE THREAD

**Issue by Chris-Pedersen** [MP-Gadget/MP-Gadget#541]
It appears this should be possible by setting `Omega_fld` and `w0_fld` in the paramfiles, and indeed I'm able to run these through `make_class_power.py` in order to generate power spectra for the ICs. But passing these paramfiles to `MP-GenIC` gives the error:

```
[ 000000.00 ] LASTMESSAGE did not end with new line: Validation of paramfile.genic failed.
Parameter `OmegaLambda` is required, but not set.
```

in the case that you do not include `OmegaLambda`, and 

```
[ 000000.00 ] ----------------------------------------------
[ 000000.00 ] Cannot have OmegaLambda and Omega_fld (evolving dark energy) at the same time!
```

In the case that you include `OmegaLambda`. The way `make_class_power.py` runs also probably isnt' ideal, as it requires both `OmegaLambda` and `Omega_fld` to be in the `paramfile.genic`. I think the script will still give the desired results provided that these are set to the same value, as it looks like `OmegaLambda` is only used in order to calculate curvature on line 85. So there is probably a simple fix here.

I'm not sure if this is the case when it comes to running with `Omega_fld` in `MP-GenIC` and `MP-Gadget` though. Is this just a matter of bypassing the first error that is currently flagged, and the rest of the code should work fine using `Omega_fld` instead of `OmegaLambda`?

Thanks!

**Comment by sbird** [comment]
If you just want Omega_fld I think you can add
OmegaLambda = 0
in the paramfile and it should work. Do you really want to use Omega_fld and OmegaLambda at the same time? I don't think there is any reason why that won't work, I just added the check because I hadn't tested it: if you can confirm that it gives a reasonable answer feel free to delete the conditions in MP-GenIC and MP-Gadget.

**Comment by sbird** [comment]
PS Not entirely sure that curvature, Omega_K, is what you expect when you use Omega_fld!

**Comment by sbird** [comment]
@Chris-Pedersen Did you work this out? Can I close the issue?
