### ISSUE TITLE
Minimum required OpenMP version to 4.5

### ISSUE THREAD

**Issue by sbird** [MP-Gadget/MP-Gadget#560]
OpenMP 4.5 (released 2015) adds support for reduction on array variables. From the standard:
"Semantics for reductions on C/C++ array sections were added and restrictions on the use of arrays and pointers in reductions were removed (see Section 2.15.3.6 on page 201)."

This would be useful in tidying up our code and making it more efficient, rather than creating explicit per-thread variable arrays and manipulating them. Currently it is used in a couple of places guarded by ifdefs, with the loop being serial if it is not found.

I would like to bump the requirement for OpenMP support to OpenMP 4.5. This is available in gcc 6+ (2016), intel 17+. (2016) and in clang 3.9, which is the first clang version to support openmp reasonably well anyway. gcc 8 is the default compiler in rhel 8 (2019) and debian stretch (oldstable 2017) has gcc 6. I think it has been long enough, but I would like to mention it here in case anyone watching has an old cluster without support for a reasonably modern compiler.

Currently we want OpenMP 4.0 for atomic capture, so this moves the minimum supported version forward by 2 years.

Options:
- Just assume OpenMP 4.5. This is cleanest and allows us to also use other OpenMP 4.5 features like taskloops if we find a use for them.
- Continue to add #pragma checks for OpenMP 4.5 Note this messes with early clang versions which support the array reduction but do not advertise OpenMP 4.5 because they do not support target offloading. In practice this would mean old compilers would continue to work but would be slower as loops would be serialised. This is likely the case anyway.
- Do not bump the version yet.

I favour option 1.

**Comment by sbird** [comment]
@rainwoodman  @andreufont Any thoughts?

**Comment by rainwoodman** [comment]
I assume Frontera is happy about this -- seems like NERSC has gcc 8 or 9
ish now based on the documentation. What about the UK cluster (DiRAC?)


- Yu

**Comment by sbird** [comment]
Yup, Frontera is cool with it (intel 19).

**Comment by andreufont** [comment]
Hi @sbird, thanks for checking! Now that neither Chris or myself are no longer in the UK, I don't expect we'll be using DIRAC anytime soon. I do hope to run new sims in a year or so, but it will be in a new machine (probably NERSC) and I think it is safe to assume that it will have modern compilers. Happy to go ahead, and thanks for the continuous development of MP-Gadget!

**Comment by sbird** [comment]
Thank you @andreufont and @rainwoodman ! I will bump the minimum version.

**Comment by sbird** [comment]
Despite your positive words, it turns out that with recent gcc the cleaned up openmp 4.5 array reduction is slower than our hand-rolled per-thread arrays. So I will not do this just yet, but thanks anyway!

**Comment by rainwoodman** [comment]
Our hand rolled per thread arrays shallows the shared array per thread. My
guess is GCC's implementation may be reusing a single array by default.
There may be a magic flag to control the memory/speed trade-off?

- Yu

**Comment by sbird** [comment]
According to https://gcc.gnu.org/onlinedocs/gcc-4.9.0/libgomp.pdf section 4.9:
"The private struct mentioned in the previous section should have a pointer to an array of
the type of the variable, indexed by the thread’s team id. The thread stores its final value
into the array, and after the barrier, the master thread iterates over the array to collect the
values."
Maybe it is slower because the memory is cache-line shared? or maybe it is heap-allocated and we are hitting some malloc contention as each thread calls malloc separately? 

I was hoping that it would do something like
master_array[5];
parallel
{
int stack_array[6];
parallel for {
stack_array[3]++;
}
(copy stack array to master_array)
}
or at least the equivalent of what we do now, but I guess not!

**Comment by rainwoodman** [comment]
On Mon, Dec 6, 2021 at 7:31 AM Simeon Bird ***@***.***> wrote:

> According to https://gcc.gnu.org/onlinedocs/gcc-4.9.0/libgomp.pdf section
> 4.9:
> "The private struct mentioned in the previous section should have a
> pointer to an array of
> the type of the variable, indexed by the thread’s team id. The thread
> stores its final value
> into the array, and after the barrier, the master thread iterates over the
> array to collect the
> values."
>
Maybe it is slower because the memory is cache-line shared? or maybe it is
> heap-allocated and we are hitting some malloc contention as each thread
> calls malloc separately?
>
Do we parallelize the collecting phase? They do master only collections.

Maybe file a bug to libgomp if we care enough about this?

- Yu

**Comment by sbird** [comment]
We do not parallelize the collecting phase. We could file a bug. Do you know where the source is?

**Comment by rainwoodman** [comment]
On Tue, Dec 7, 2021 at 3:38 PM Simeon Bird ***@***.***> wrote:

> We do not parallelize the collecting phase. We could file a bug. Do you
> know where the source is?
>
>
I took a quick search and couldn't find the exact location of the code.
Seems to be near

https://github.com/gcc-mirror/gcc/blob/master/libgomp/parallel.c#L189

This appears to be the ticket system:
https://gcc.gnu.org/bugzilla/
The guide is https://gcc.gnu.org/projects/gomp/; which basically says
filling under the gomp component.

**Comment by sbird** [comment]
Maybe here: https://github.com/gcc-mirror/gcc/blob/master/libgomp/task.c#L2134 ?

**Comment by sbird** [comment]
Maybe the slow part is this line: https://github.com/gcc-mirror/gcc/blob/master/libgomp/task.c#L2155
and the memset. In which case we are faster just because we can get heap memory with zero fragmentation.
