### ISSUE TITLE
MP-GenIC compilation error on macOS (with simple workaround?)

### ISSUE THREAD

**Issue by freddavies** [MP-Gadget/MP-Gadget#564]
When compiling MP-Gadget on my Mac laptop (running the archaic OS version 10.14.6, with GCC 8.3), most of the code compiles without any problems, except for MP-GenIC where the `All` declaration from `libgadget/allvars.h` is not being recognized for some reason:

```
cd genic; /Applications/Xcode.app/Contents/Developer/usr/bin/make
mpicc -fopenmp -O3 -g -Wall -ffast-math .objs/main.o .objs/params.o ../libgenic/libgenic.a ../libgadget/libgadget.a ../libgadget/libgadget-utils.a -lm -L/usr/local/lib -lgsl -lgslcblas -lm -L../depends/lib -lbigfile-mpi -lbigfile -lpfft_omp -lfftw3_mpi -lfftw3_omp -lfftw3 -o MP-GenIC
Undefined symbols for architecture x86_64:
  "_All", referenced from:
      _hybrid_nu_gravpm_is_active in libgadget.a(gravpm.o)
      __prepare._omp_fn.1 in libgadget.a(gravpm.o)
      _compute_neutrino_power in libgadget.a(gravpm.o)
      __prepare in libgadget.a(gravpm.o)
      _potential_transfer in libgadget.a(gravpm.o)
      _gravpm_init_periodic in libgadget.a(gravpm.o)
      _gravpm_force in libgadget.a(gravpm.o)
      ...
     (maybe you meant: _MPIU_Alltoallv, _MPI_Alltoallv_sparse , _MPI_Alltoallv_smart )
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [MP-GenIC] Error 1
make: *** [all] Error 2
```

A simple workaround exists: eschew `libgadget.a` entirely and directly include the `libgadget/.objs` files one by one in `genic/Makefile`, like so:

```
# Customization; see Options.mk.example
CONFIG ?= ../Options.mk

include $(CONFIG)

INCL=../libgadget/config.h

include ../Makefile.rules

OBJS = main.o params.o

OBJS := $(OBJS:%.o=.objs/%.o)

OBJS_gadget = ../libgadget/.objs/gdbtools.o ../libgadget/.objs/hci.o ../libgadget/.objs/fof.o ../libgadget/.objs/fofpetaio.o ../libgadget/.objs/petaio.o ../libgadget/.objs/domain.o ../libgadget/.objs/exchange.o ../libgadget/.objs/slotsmanager.o ../libgadget/.objs/partmanager.o ../libgadget/.objs/blackhole.o ../libgadget/.objs/timebinmgr.o ../libgadget/.objs/run.o ../libgadget/.objs/drift.o ../libgadget/.objs/stats.o ../libgadget/.objs/timestep.o ../libgadget/.objs/init.o ../libgadget/.objs/checkpoint.o ../libgadget/.objs/sfr_eff.o ../libgadget/.objs/cooling.o ../libgadget/.objs/cooling_rates.o ../libgadget/.objs/cooling_uvfluc.o ../libgadget/.objs/cooling_qso_lightup.o ../libgadget/.objs/winds.o ../libgadget/.objs/density.o ../libgadget/.objs/metal_return.o ../libgadget/.objs/treewalk.o ../libgadget/.objs/cosmology.o ../libgadget/.objs/gravshort-tree.o ../libgadget/.objs/gravshort-pair.o ../libgadget/.objs/hydra.o ../libgadget/.objs/timefac.o ../libgadget/.objs/gravpm.o ../libgadget/.objs/powerspectrum.o ../libgadget/.objs/forcetree.o ../libgadget/.objs/petapm.o ../libgadget/.objs/gravity.o ../libgadget/.objs/densitykernel.o ../libgadget/.objs/lightcone.o ../libgadget/.objs/walltime.o ../libgadget/.objs/runtests.o ../libgadget/.objs/neutrinos_lra.o ../libgadget/.objs/omega_nu_single.o ../libgadget/.objs/config.o

all: MP-GenIC

MP-GenIC: $(OBJS) ../libgenic/libgenic.a $(OBJS_gadget) ../libgadget/libgadget-utils.a
	$(MPICC) $(OPTIMIZE) $^ $(LIBS) -o $@

clean:
	rm -rf $(OBJS) MP-GenIC
```

Any ideas why the `libgadget.a` library is not working correctly here? Or is it just attributable to Mac weirdness, which may not even affect more recent OS versions? Even though I found a workaround, I thought I should make an issue in case anyone else has the same problem.

**Comment by sbird** [comment]
It is a linker problem and those are usually...arcane. Especially I don't know why MP-Gadget (which also uses the All struct) is compiling fine, why the only link error is in gravpm.o (the symbol is in init.o) and why this only happens on Mac.

The real solution is to continue the refactor to split the global All struct and pass the data around locally instead of a messy global. Another thing that might work is to try compiling at a lower optimisation level, as sometimes these things happen because the linker is optimising the object away.

Glad to know you are using it on Mac (no-one else has done that). I'd be happy if you can confirm whether the threading works properly.

**Comment by sbird** [comment]
PR https://github.com/MP-Gadget/MP-Gadget/pull/565 might fix it. It removes the dependency of gravpm.o on the allvars symbol. I kind of suspect that the problem will just resurface somewhere else, but it's worth a try.
