### ISSUE TITLE
Memory Usage Guidelines for DM Only simulations

### ISSUE THREAD

**Issue by kb-devacct** [MP-Gadget/MP-Gadget#588]
Hi, I wasn't sure where to ask for help about MP-Gadget so hopefully creating this issue is okay. 

I'm having some trouble understanding how much memory to plan for a DM only simulation run. The user guide for MP-Gadget points me to the Gadget-2 paper which says plan ~80bytes per particle. When I run it uses way more than that. 

Examples:
- 512^3, MP-Genic used 50GB
- 1024^3 MP-Genic used 500GB
- 512^3 MP-Gadget used 250GB
- 1024^3 MP-Gadget crashed after 2 timestpes, allocated 3TB!

I am running this on an HPC cluster with Slurm which I think I might be configuring incorrectly. 
- 64 nodes (Physical machines in the cluster)
- 50GB mem per node
- 1 task (MP-Gadget instance) per node
- 2 logical CPUs per task (This might be where I'm going wrong as there's up to 70 CPUs per node available)

If you could help me answer these two questions: 
- What's the expected memory usage for DM only 1024^3 particles? 
- Slurm configuration ideas? If I use 1 task per node but use all CPUs available, will that help the memory usage?

Thanks for you help!

**Comment by sbird** [comment]
Hi, this is indeed the right place to ask. The Gadget-2 paper is indeed a bit out of date (I think that is running with single precision quantities). The code memory usage is configurable, however. 

The code prints real memory requirements per particle on startup, which depend on whether you are using DEBUG and right now for me are:

[ 000000.00 ] Size of particle structure       168  [bytes]     <- This is for DM-only.
[ 000000.00 ] Size of blackhole structure       208  [bytes]
[ 000000.00 ] Size of sph particle structure   176  [bytes]
[ 000000.00 ] Size of star particle structure   96  [bytes]

The code needs memory for the number of particles it has initially, plus a bit more for imbalance and star formation, which is controlled by the parameter PartAllocFactor. By default this is 1.5, but for pure DM with no star formation you can make it a bit smaller, maybe as low as 1.1. In addition, the PM code needs extra memory for the Fourier grids during a PM step, about:
4 x Nmesh x 8 bytes. By default Nmesh is 3 x Npart, but if you are short on memory you can reduce it. 2x Npart will give the same results, it will just be a little slower. There are also a few other allocations but they are either small or not really necessary, in the sense that if memory is low it will just make them smaller at some compute cost. The total should be about 10% higher than that.

Note that unless you have VALGRIND defined, the code pre-allocates 0.6 of the available memory at startup, to avoid fragmentation. So the memory usage shown in top will not be accurate. If the code runs out of memory, it will print a message explaining which allocation caused it to run out, which can help you know which parameter to change.

I'll add the above to the user guide. If I'm counting correctly I am still a factor of two too low compared to your peak usage: are you sure it is not a simulation with some gas particles? If you post the error message it gives on exit I could perhaps be more helpful.

**Comment by sbird** [comment]
PS The best way to run the code is indeed to use shared memory as much as possible: so 1 task per physical socket (usually 2 tasks per node) and then 1 thread for every physical CPU on the socket.

**Comment by sbird** [comment]
Yup, that's definitely dark matter only. Glad you got the memory sorted out. Your memory usage sounds reasonable: my numbers were just ballpark and it uses available memory when it can to make the transfers faster.
