### ISSUE TITLE
Bug in tools/readBHdetail.py

### ISSUE THREAD

**Issue by VarunNikam22** [MP-Gadget/MP-Gadget#612]
I tried to read the binary files storing properties for all active blackholes from BlackholeDetails* folder in the output...just wanted to point out that the content dictionary defined in the code on Master/tools/readBHdetail.py has the KEflag Ctype specifier defined as double instead of integer.

Although I corrected it in my code, I wished to publish a modified version of  the script with minor optimizations for file and error handling.

**Comment by sbird** [comment]
Well noticed. Would you like to submit a PR with the fix? We can take it and then you would get some 'credit' for it. Happy to take the modified version as well.

**Comment by VarunNikam22** [comment]
Sure, I have submitted a PR through my forked repo. This is my first time at this, let me know if there's anywhere I can improve

**Comment by sbird** [comment]
That was perfect, thank you!
