### ISSUE TITLE
Vectorize SPH

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#62]
Two potential places:

- distance
- kernel

Why don't we convert the kernel to a look up table?

Volker recommended http://www.agner.org/optimize/#vectorclass

I would prefer auto vectorization. But in any case applying vectorization means rewriting the NgbIter functions to take vectorized inputs. So that should be done first.

**Comment by sbird** [comment]
I gave this a try (converting the kernel to a lookup table) but it did not help. The SPH code seems to be limited by the latency to fetch sph_particle_data (one entry of which is three cachelines) into cache. 

I'm trying to speed this up by shrinking sph_particle_data and removing some of the conditionals, which might also help auto-vectorization.
