### ISSUE TITLE
Preserve swallowed particles in snapshot files.

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#67]
The only way to make sure the full swallowing history is preserved is to keep swallowed particles in the snapshot files. They shall carry an attribute 'SwallowerID', which is the swallower.

We need to rework the garbage detection code to support this. We need to add IsGarbage for truely removed particles. IsGarbage.

(Mass == 0) will still skip all interactions.

Gas swallowing will produce garbages. BH swallowing will not. We shall be able to track merger history with this.

**Comment by sbird** [comment]
We have IsGarbage now: we need to change the force tree build, drift and timestep parts of the code to not look at Swallowed particles, and then stop marking these particles Garbage. We should also change the writing code to mark them garbage after IO is done. Let's first do this for BH particles (type 5) only, as it is easiest.
