### ISSUE TITLE
PETAPM=2,3 produces substantially different power to  PETAPM=1

### ISSUE THREAD

**Issue by sbird** [MP-Gadget/MP-Gadget#70]
I was running a test (pure DM, 96^3 particles, z=99 -> z=0, Nmesh=192) with both PETAPM=1 and PETAPM=2,3 and I noticed that there is much less power with PETAPM = 3 than with PETAPM=1: it looks like a correction for a window function is missing somewhere?

See this plot: 
[pks_r_camb-002.pdf](https://github.com/rainwoodman/MP-Gadget/files/982981/pks_r_camb-002.pdf)

which is the powr at z=10 (still linear) compared to CAMB. Green is PETAPM=1, blue is PETAPM=2.
It is worse for PETAPM=3. For comparison, here is a similar branch with Gadget-2:

[pks_r_camb-002.pdf](https://github.com/rainwoodman/MP-Gadget/files/982986/pks_r_camb-002.pdf)

so you can see that even PETAPM = 1 loses some power.

To reproduce, use the yufeng branch, as some fixes have gone into that already.

**Comment by rainwoodman** [comment]
I know that PETAPM > 1 gave less intermediate scale power.
PETAPM == 1 is the finite differentiation of Gadget in fourier space. It is a 4 point differentiation.

Using any higher order differentiation the gradient field is smoother than the ideal kernel.
This will show up as a defecit in intermidate scale force (due to the short range being accurate). I do not think this issue was addressed in Gadget neither. Increasing the PM size will help. Or going to a lower order differentiation scheme (ik / k**2) (and rely on the long range smoothing to erase the noise) Give it a go?

**Comment by sbird** [comment]
Ah, indeed, Gadget-2 is the same as PETAPM=1; I was running my test with a lower PMGRID value. Silly me. Increasing Nmesh further (it is already 2*MeanSeparation) doesn't make a difference. 

Going to a lower order diff. scheme (ik/k^2) does make it better but there is clearly more noise.

If this is a known feature, then that's ok. It is near the mean particle spacing anyway.

My question is: given that higher order kernels lose intermediate power, should we be recommending them in gravpm.c? Or do they have some other advantage in the accuracy of the short range force that makes up for it?

**Comment by rainwoodman** [comment]
Why do you say ik/k^2 has more noise?

The long range force gaussian will smooth out all noises wouldn't it? I would think in that case we actually want ik/k^2, not any other kernels not even the four point kernel.

We surely shall not recommend higher order kernels in gravpm -- I think we shall probably even remove them -- in a quasi-nbody code it may be useful, but not here.

**Comment by sbird** [comment]
ik/k^2 is slightly above the CAMB prediction at early times (slightly) - I interpreted that as noise bleeding from the grid scale, but it is a very small difference, so maybe it is not extra noise. 

Actually ik/k^2 is fairly close to the 4-point:
[pks_r_camb-002.pdf](https://github.com/rainwoodman/MP-Gadget/files/986542/pks_r_camb-002.pdf)
green is ik/k^2, blue is PETAPM=1. I can see arguments for using it and arguments for retaining gadget-2 compatibility.

I pushed commits to remove the recommendation for PETAPM=3 (5481d07) and remove PETAPM>1 (820e194) to the latest cleanup branch. Let me know if you want to use ik/k^2 as well.

**Comment by rainwoodman** [comment]
We have evidence that ik/k^2 is more correct than the 4 point function when blending with short range force then? Green is also slightly better at large scale, for some reason?

**Comment by sbird** [comment]
Yes, some evidence - but not that much. The large scale difference is probably unrelated. The simulations also have a different neutrino mass (although each is divided by the CAMB power appropriate for their cosmology), and that probably accounts for it.

**Comment by rainwoodman** [comment]
I can work out the exact short range kernel for CIC+PETAPM=1, 2, 3 without the gaussian smoothing. But will this be an improvement or not?

**Comment by rainwoodman** [comment]
No I actually failed at this. I was playing with this in a 1d box of size 1.0 per side. For a single charge particle at the center. I couldn't even match the potential computed from a mesh and that from the direct calculation (after re normalization).

![image](https://user-images.githubusercontent.com/138060/33914054-306a7f3a-df51-11e7-92cb-f65050381937.png)
Here is the ratio -- it doesn't go to 1 at inifinity (where the field is weak).

![image](https://user-images.githubusercontent.com/138060/33914079-4ee2285a-df51-11e7-9d9d-576081dc6158.png)

Perhaps the poisson equation in 1d is different?

**Comment by sbird** [comment]
As well as setting Nmesh = 3* Npart (which you suggested somewhere else that I can't find now) we could also try making Asmth smaller. I noticed that https://arxiv.org/abs/1610.08501 uses Asmth = 0.125 and thus avoids the particle coupling from the tree. We should do some force tests first though

**Comment by sbird** [comment]
Since we match the short-range and long-range kernels now, I think we close this one.
