### ISSUE TITLE
FOF Rewrite

### ISSUE THREAD

**Issue by rainwoodman** [MP-Gadget/MP-Gadget#8]
Rewrite FOF along the lines of https://github.com/bccp/nbodykit/blob/master/nbodykit/fof.py

The code there was cryptic; but less cryptic than the version in Gadget. This new fof will be the basis of the model in gal_particle.

Currently we are able to assign MinID[Head] globally, correctly. Further changes:
1) Globally calculate the halo id based on MinID[Head]. This can be easily done if we do not insist MinID to be particle ID, but use a global particle index instead (~about mpsort_mpi calls)
2) Calculate FOFGroup properties based on the halo id of particles
2.1) First do center of mass and potential min
2.2) then do angular momentum etc
3) BH seeding will be rewritten. (along the gal_particle head)

**Comment by sbird** [comment]
I think Yu did this - shall we close the bug?

**Comment by rainwoodman** [comment]
Yes I think this has been done.
